// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Seq__Test from "../src/Seq__Test.mjs";
import * as Seq__Result from "../src/Seq__Result.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function expectEqual(title, expectation, a, b) {
  return Seq__Test.fromPredicate("Result", title, expectation, () => Primitive_object.equal(a(), b));
}

let fromTryCatch = [
  Seq__Test.fromPredicate("Result", "fromTryCatch", "when throw, return as Error", () => {
    let r = Seq__Result.fromTryCatch(() => Exn.raiseError("banana"));
    if (r.TAG === "Ok") {
      return false;
    }
    let err = Exn.asJsExn(r._0);
    if (err !== undefined) {
      return Primitive_object.equal(Primitive_option.valFromOption(err).message, "banana");
    } else {
      return false;
    }
  }),
  Seq__Test.fromPredicate("Result", "fromTryCatch", "when not throw, return result as Ok", () => Primitive_object.equal(Seq__Result.fromTryCatch(() => 3), {
    TAG: "Ok",
    _0: 3
  }))
];

let toOption = [
  expectEqual("toOption", "when Ok, return Some", () => Seq__Result.toOption({
    TAG: "Ok",
    _0: 4
  }), 4),
  expectEqual("toOption", "when Error, return None", () => Seq__Result.toOption({
    TAG: "Error",
    _0: 4
  }), undefined)
];

let allTests = [
  toOption,
  fromTryCatch
].flat();

let T;

let R;

export {
  T,
  R,
  expectEqual,
  fromTryCatch,
  toOption,
  allTests,
}
/* fromTryCatch Not a pure module */
