// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Seq__Test from "../src/Seq__Test.mjs";
import * as Seq__Option from "../src/Seq__Option.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

function expectEq(title, expectation, a, b) {
  return Seq__Test.fromPredicate("Option", title, expectation, () => Primitive_object.equal(a(), b));
}

function add(a, b) {
  return a + b | 0;
}

function add3(a, b, c) {
  return (a + b | 0) + c | 0;
}

function add4(a, b, c, d) {
  return ((a + b | 0) + c | 0) + d | 0;
}

let tests = [
  expectEq("map2", "when 0/2 Some => None", () => Seq__Option.map2(undefined, undefined, add), undefined),
  expectEq("map2", "when 2/2 Some => Some with map args", () => Seq__Option.map2(1, 5, add), 6),
  expectEq("map2", "when 1/2 is Some => None", () => Seq__Option.map2(1, undefined, add), undefined),
  expectEq("map2", "when 1/2 is Some => None", () => Seq__Option.map2(undefined, 1, add), undefined),
  expectEq("map3", "when 3/3 is Some => Some with map args", () => Seq__Option.map3(1, 5, 9, add3), 15),
  expectEq("map3", "when 2/3 is Some => None", () => Seq__Option.map3(1, undefined, 5, add3), undefined),
  expectEq("map3", "when 1/3 is Some => None", () => Seq__Option.map3(undefined, 1, undefined, add3), undefined),
  expectEq("map3", "when 0/3 is Some => None", () => Seq__Option.map3(undefined, undefined, undefined, add3), undefined)
];

let T;

let O;

export {
  expectEq,
  T,
  O,
  add,
  add3,
  add4,
  tests,
}
/* tests Not a pure module */
