// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Seq from "../src/Seq.mjs";
import * as List from "rescript/lib/es6/List.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Result from "rescript/lib/es6/Result.js";
import * as Seq__Test from "../src/Seq__Test.mjs";
import * as Seq__Result from "../src/Seq__Result.mjs";
import * as Primitive_int from "rescript/lib/es6/Primitive_int.js";
import * as Seq__SeqSamples from "../src/Seq__SeqSamples.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function characters(s) {
  return Seq.fromArray(undefined, undefined, s.split(""));
}

function joinInts(xs) {
  return xs.map(__x => __x.toString()).join("");
}

function shorten(s) {
  return s.slice(0, 1000);
}

function trueAlways(param) {
  return true;
}

function falseAlways(param) {
  return false;
}

function callCount() {
  let count = {
    contents: 0
  };
  return () => {
    count.contents = count.contents + 1 | 0;
    return count.contents;
  };
}

function callCountForever() {
  return Seq.foreverWith(callCount());
}

function throwIfInvoked() {
  return Exn.raiseError("Tried to invoke a testing function that always fails.");
}

function death() {
  return Seq.onceWith(throwIfInvoked);
}

function toDispenser(xx) {
  let xx$1 = {
    contents: xx
  };
  return () => {
    let match = Seq.uncons(xx$1.contents);
    if (match !== undefined) {
      xx$1.contents = match[1];
      return match[0];
    } else {
      return Exn.raiseError("You are attempting to consume a value past the end of a sequence.");
    }
  };
}

function countdown(n) {
  if (n < 0) {
    throw {
      RE_EXN_ID: Seq.InvalidArgument,
      _1: "The countdown must begin at 0 or more.",
      Error: new Error()
    };
  }
  let count = {
    contents: n
  };
  return () => {
    if (count.contents === 0) {
      Exn.raiseError("Attempted to consume a value from the countdown after it had been exhausted.");
    }
    count.contents = count.contents - 1 | 0;
    return count.contents + 1 | 0;
  };
}

function seqEqual(title, expectation, a, b) {
  return Seq__Test.fromResult("Seq", title, expectation, () => {
    let a$1 = Seq.toArray(a());
    if (Primitive_object.equal(a$1, b)) {
      return {
        TAG: "Ok",
        _0: undefined
      };
    } else {
      return {
        TAG: "Error",
        _0: "Actual:   " + a$1.toString().slice(0, 1000) + "\nExpected: " + b.toString().slice(0, 1000)
      };
    }
  });
}

function valueEqual(title, expectation, a, b) {
  return Seq__Test.fromResult("Seq", title, expectation, () => {
    let aValue = a();
    if (Primitive_object.equal(aValue, b)) {
      return {
        TAG: "Ok",
        _0: undefined
      };
    } else {
      return {
        TAG: "Error",
        _0: "Actual:   " + aValue + "\nExpected: " + b
      };
    }
  });
}

function willThrow(title, expectation, f) {
  return Seq__Test.expectThrow("Seq", title, expectation, f);
}

function willNotThrow(title, expectation, f) {
  return Seq__Test.fromPredicate("Seq", title, expectation, () => Result.isOk(Seq__Result.fromTryCatch(f)));
}

function makeSeqEqualsTests(title, xs) {
  return xs.map((param, inx) => {
    let source = param[0];
    return seqEqual(title, "index " + inx.toString() + " " + param[2], () => source, param[1]);
  });
}

function makeValueEqualTests(title, tests) {
  return tests.map((param, index) => valueEqual(title, "Index " + index.toString() + " " + param[2], param[0], param[1]));
}

let onceTests = [
  seqEqual("once", "string", () => Seq.once("x"), ["x"]),
  seqEqual("once", "bool", () => Seq.once(true), [true]),
  seqEqual("once", "int", () => Seq.once(1), [1]),
  seqEqual("once", "object", () => Seq.once({
    a: 1
  }), [{
      a: 1
    }]),
  seqEqual("once", "array", () => Seq.once([
    1,
    2,
    3
  ]), [[
      1,
      2,
      3
    ]])
];

let onceWithTests = [
  seqEqual("onceWith", "string", () => Seq.onceWith(() => "x"), ["x"]),
  seqEqual("onceWith", "bool", () => Seq.onceWith(() => true), [true]),
  seqEqual("onceWith", "object", () => Seq.once({
    a: 1
  }), [{
      a: 1
    }]),
  seqEqual("onceWith", "array", () => Seq.onceWith(() => [
    1,
    2
  ]), [[
      1,
      2
    ]]),
  valueEqual("onceWith", "generator function only called when enumerated", () => {
    Seq.onceWith(throwIfInvoked);
    return 1;
  }, 1),
  seqEqual("onceWith", "generator function called one time at most", () => Seq.onceWith(countdown(1)), [1])
];

let emptyTests = [seqEqual("empty", "has no items", () => Seq.empty, [])];

let consTests = [
  seqEqual("cons", "when a + empty => a", () => Seq.cons(1, Seq.empty), [1]),
  seqEqual("cons", "when a + bcd => abcd", () => Seq.cons(1, Seq.range(2, 4)), [
    1,
    2,
    3,
    4
  ])
];

let fromListTests = makeSeqEqualsTests("fromList", [
  [
    Seq.fromList({
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: {
            hd: 4,
            tl: {
              hd: 5,
              tl: /* [] */0
            }
          }
        }
      }
    }),
    [
      1,
      2,
      3,
      4,
      5
    ],
    "many"
  ],
  [
    Seq.fromList({
      hd: 1,
      tl: /* [] */0
    }),
    [1],
    "one item"
  ],
  [
    Seq.fromList(/* [] */0),
    [],
    "empty"
  ]
]);

let cycleTests = makeSeqEqualsTests("cycle", [
  [
    Seq.cycle(Seq.empty),
    [],
    "when empty => empty"
  ],
  [
    Seq.take(Seq.cycle(Seq.once(1)), 4),
    [
      1,
      1,
      1,
      1
    ],
    ""
  ],
  [
    Seq.take(Seq.cycle(Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ])), 9),
    [
      1,
      2,
      3,
      1,
      2,
      3,
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.take(Seq.cycle(Seq.forever(1)), 4),
    [
      1,
      1,
      1,
      1
    ],
    "when infinite can still cycle"
  ],
  [
    Seq.take(Seq.cycle(Seq.take(Seq.foreverWith(callCount()), 3)), 9),
    [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9
    ],
    "the process to generate items is cycled, not the items themselves."
  ],
  [
    Seq.take(Seq.cycle(Seq.cache(Seq.take(Seq.foreverWith(callCount()), 3))), 6),
    [
      1,
      2,
      3,
      1,
      2,
      3
    ],
    "can use cache to cycle values, not the process."
  ]
]).concat([
  valueEqual("cycle", "empty determination is lazy", () => {
    Seq.cycle(Seq.tap(Seq.foreverWith(throwIfInvoked), param => {
      console.log("hmm...");
    }));
    return 1;
  }, 1),
  valueEqual("cycle", "millions", () => Seq.last(Seq.take(Seq.cycle(Seq.range(1, 1000)), 1000000)), 1000)
]);

let allPairsTests = makeSeqEqualsTests("allPairs", [
  [
    Seq.allPairs(Seq.empty, Seq.empty),
    [],
    ""
  ],
  [
    Seq.allPairs(Seq.empty, Seq.range(4, 6)),
    [],
    ""
  ],
  [
    Seq.allPairs(Seq.once(1), Seq.once(2)),
    [[
        1,
        2
      ]],
    ""
  ],
  [
    Seq.allPairs(Seq.once(1), Seq.range(4, 6)),
    [
      [
        1,
        4
      ],
      [
        1,
        5
      ],
      [
        1,
        6
      ]
    ],
    ""
  ],
  [
    Seq.allPairs(Seq.range(4, 6), Seq.once(1)),
    [
      [
        4,
        1
      ],
      [
        5,
        1
      ],
      [
        6,
        1
      ]
    ],
    ""
  ],
  [
    Seq.allPairs(Seq.range(1, 3), Seq.range(4, 6)),
    [
      [
        1,
        4
      ],
      [
        1,
        5
      ],
      [
        1,
        6
      ],
      [
        2,
        4
      ],
      [
        2,
        5
      ],
      [
        2,
        6
      ],
      [
        3,
        4
      ],
      [
        3,
        5
      ],
      [
        3,
        6
      ]
    ],
    ""
  ],
  [
    Seq.allPairs(Seq.replicateWith(countdown(2), 2), Seq.replicateWith(countdown(2), 2)),
    [
      [
        2,
        2
      ],
      [
        2,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        1
      ]
    ],
    "cached!"
  ]
]);

let rangeTests = makeSeqEqualsTests("range", [
  [
    Seq.range(1, 1),
    [1],
    ""
  ],
  [
    Seq.range(1, 2),
    [
      1,
      2
    ],
    ""
  ],
  [
    Seq.range(4, 6),
    [
      4,
      5,
      6
    ],
    ""
  ],
  [
    Seq.range(6, 1),
    [
      6,
      5,
      4,
      3,
      2,
      1
    ],
    ""
  ],
  [
    Seq.range(-3, 3),
    [
      -3,
      -2,
      -1,
      0,
      1,
      2,
      3
    ],
    ""
  ]
]);

let rangeMapTests = makeSeqEqualsTests("rangeMap", [
  [
    Seq.rangeMap(1, 1, __x => __x.toString()),
    ["1"],
    ""
  ],
  [
    Seq.rangeMap(1, 2, __x => __x.toString()),
    [
      "1",
      "2"
    ],
    ""
  ],
  [
    Seq.rangeMap(4, 6, __x => __x.toString()),
    [
      "4",
      "5",
      "6"
    ],
    ""
  ],
  [
    Seq.rangeMap(6, 1, __x => __x.toString()),
    [
      "6",
      "5",
      "4",
      "3",
      "2",
      "1"
    ],
    ""
  ],
  [
    Seq.rangeMap(-3, 3, __x => __x.toString()),
    [
      "-3",
      "-2",
      "-1",
      "0",
      "1",
      "2",
      "3"
    ],
    ""
  ]
]);

let concatTests = makeSeqEqualsTests("concat", [
  [
    Seq.concat(Seq.range(1, 3), Seq.range(4, 6)),
    [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    ""
  ],
  [
    Seq.concat(Seq.empty, Seq.range(1, 3)),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.concat(Seq.range(1, 3), Seq.empty),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.concat(Seq.empty, Seq.empty),
    [],
    ""
  ],
  [
    Seq.append(Seq.range(1, 3), Seq.range(4, 6)),
    [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    ""
  ],
  [
    Seq.append(Seq.empty, Seq.range(1, 3)),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.append(Seq.range(1, 3), Seq.empty),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.append(Seq.empty, Seq.empty),
    [],
    ""
  ]
]);

let prependTests = makeSeqEqualsTests("prepend", [
  [
    Seq.prepend(Seq.range(1, 3), Seq.range(4, 6)),
    [
      4,
      5,
      6,
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.prepend(Seq.empty, Seq.range(1, 3)),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.prepend(Seq.range(1, 3), Seq.empty),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.prepend(Seq.empty, Seq.empty),
    [],
    ""
  ]
]);

let flatMapTests = makeSeqEqualsTests("flatMap", [
  [
    Seq.flatMap(Seq.empty, i => Seq.replicate(i, i)),
    [],
    ""
  ],
  [
    Seq.flatMap(Seq.once(2), i => Seq.replicate(6, i)),
    [
      6,
      6
    ],
    ""
  ],
  [
    Seq.flatMap(Seq.once(2), param => Seq.empty),
    [],
    ""
  ],
  [
    Seq.flatMap(Seq.range(1, 3), i => Seq.replicate(i, i)),
    [
      1,
      2,
      2,
      3,
      3,
      3
    ],
    ""
  ],
  [
    Seq.flatMap(Seq.range(1, 3), param => Seq.empty),
    [],
    ""
  ],
  [
    Seq.flatMap(Seq.range(1, 3), Seq.once),
    [
      1,
      2,
      3
    ],
    ""
  ]
]).concat([valueEqual("flatMap", "million won't overflow", () => Seq.last(Seq.concat(Seq.flatMap(Seq.replicate(1, 1000), param => Seq.replicate(1, 1000)), Seq.once(999))), 999)]);

let mapTests = makeSeqEqualsTests("map", [
  [
    Seq.map(Seq.range(1, 5), i => i + 1 | 0),
    [
      2,
      3,
      4,
      5,
      6
    ],
    ""
  ],
  [
    Seq.map(Seq.once(1), i => i + 1 | 0),
    [2],
    ""
  ],
  [
    Seq.map(Seq.empty, i => i + 1 | 0),
    [],
    ""
  ],
  [
    Seq.mapi(Seq.range(1, 3), (n, inx) => Math.imul(n, inx)),
    [
      0,
      2,
      6
    ],
    ""
  ]
]);

let indexedTests = makeSeqEqualsTests("indexed", [
  [
    Seq.indexed(Seq.range(1, 3)),
    [
      [
        1,
        0
      ],
      [
        2,
        1
      ],
      [
        3,
        2
      ]
    ],
    ""
  ],
  [
    Seq.indexed(Seq.once(9)),
    [[
        9,
        0
      ]],
    ""
  ],
  [
    Seq.indexed(Seq.empty),
    [],
    ""
  ]
]);

let takeWhileTests = makeSeqEqualsTests("takeWhile", [
  [
    Seq.takeWhile(Seq.range(1, 5), i => i <= 3),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.takeWhile(Seq.range(1, 5), i => i === 1),
    [1],
    ""
  ],
  [
    Seq.takeWhile(Seq.range(1, 5), param => false),
    [],
    ""
  ],
  [
    Seq.takeWhile(Seq.range(1, 5), i => i <= 5),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.takeWhile(Seq.empty, param => true),
    [],
    ""
  ],
  [
    Seq.takeWhile(Seq.range(1, 5), param => false),
    [],
    ""
  ]
]);

let dropTests = makeSeqEqualsTests("drop", [
  [
    Seq.drop(Seq.range(1, 3), 0),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.drop(Seq.range(1, 3), 1),
    [
      2,
      3
    ],
    ""
  ],
  [
    Seq.drop(Seq.range(1, 3), 3),
    [],
    ""
  ],
  [
    Seq.drop(Seq.range(1, 3), 4),
    [],
    ""
  ],
  [
    Seq.drop(Seq.empty, 0),
    [],
    ""
  ],
  [
    Seq.drop(Seq.empty, 1),
    [],
    ""
  ],
  [
    Seq.drop(Seq.once(4), 0),
    [4],
    ""
  ],
  [
    Seq.drop(Seq.once(4), 1),
    [],
    ""
  ]
]).concat([
  willNotThrow("drop", "lazy", () => Seq.drop(Seq.onceWith(throwIfInvoked), 1)),
  valueEqual("drop", "if drop 0, return same seq instance", () => {
    let oneToFive = Seq.range(1, 5);
    return Seq.drop(oneToFive, 0) === oneToFive;
  }, true),
  valueEqual("drop", "while drop a million, no overflow", () => Seq.last(Seq.drop(Seq.concat(Seq.range(1, 999999), Seq.once(1000000)), 999999)), 1000000)
]);

let flattenTests = makeSeqEqualsTests("flatten", [
  [
    Seq.flatten(Seq.once(Seq.empty)),
    [],
    ""
  ],
  [
    Seq.flatten(Seq.map(Seq.range(1, 3), i => Seq.replicate(i, i))),
    [
      1,
      2,
      2,
      3,
      3,
      3
    ],
    ""
  ],
  [
    Seq.flatten(Seq.empty),
    [],
    ""
  ]
]);

function merge(nums1, nums2, nums3) {
  return seqEqual("sortedMerge", "", () => Seq.sortedMerge(Seq.fromArray(undefined, undefined, nums1), Seq.fromArray(undefined, undefined, nums2), Primitive_int.compare), nums3);
}

let sortedMergeTests = [
  merge([], [], []),
  merge([], [
    1,
    2,
    3
  ], [
    1,
    2,
    3
  ]),
  merge([
    1,
    2,
    3
  ], [], [
    1,
    2,
    3
  ]),
  merge([
    1,
    2,
    3
  ], [
    1,
    2,
    3
  ], [
    1,
    1,
    2,
    2,
    3,
    3
  ]),
  merge([
    4,
    5,
    6
  ], [
    1,
    2,
    3
  ], [
    1,
    2,
    3,
    4,
    5,
    6
  ]),
  merge([
    1,
    1,
    3,
    6,
    6,
    8,
    8,
    9
  ], [
    0,
    2,
    2,
    7,
    9
  ], [
    0,
    1,
    1,
    2,
    2,
    3,
    6,
    6,
    7,
    8,
    8,
    9,
    9
  ])
];

let tapTests = [
  valueEqual("tap", "can inspect every value", () => {
    let seen = [];
    Seq.consume(Seq.tap(Seq.range(1, 5), i => {
      seen.push(i);
    }));
    return seen;
  }, [
    1,
    2,
    3,
    4,
    5
  ]),
  willNotThrow("tap", "lazy", () => Seq.tap(Seq.onceWith(throwIfInvoked), param => {
    console.log("Boom!");
  }))
];

let windowTests = Seq.toArray(Seq.flatten(Seq.rangeMap(0, 6, sourceLength => Seq.rangeMap(1, 8, windowSize => {
  let source = sourceLength === 0 ? Seq.empty : Seq.range(1, sourceLength);
  let result = Seq.window(source, windowSize);
  if (windowSize > sourceLength || sourceLength === 0) {
    return valueEqual("window", "when windowSize == 0 or > source length => 0 results", () => Seq.length(result), 0);
  }
  let expected = Seq.rangeMap(1, (sourceLength - windowSize | 0) + 1 | 0, i => Seq.toArray(Seq.range(i, (i + windowSize | 0) - 1 | 0)));
  return valueEqual("window", "source length " + sourceLength.toString() + ", window size " + windowSize.toString(), () => Seq.equals(result, expected, Primitive_object.equal), true);
})))).concat([
  willNotThrow("window", "lazy", () => Seq.window(Seq.onceWith(throwIfInvoked), 5)),
  willNotThrow("window", "millions for size", () => Seq.consume(Seq.window(Seq.range(1, 100), 999999))),
  willThrow("window", "when size = 0 => throw", () => Seq.consume(Seq.window(Seq.range(1, 5), 0))),
  willThrow("window", "when size < 0 => throw", () => Seq.consume(Seq.window(Seq.range(1, 5), -1))),
  valueEqual("window", "each window shares same instance", () => Seq.every(Seq.pairwise(Seq.window(Seq.range(1, 5), 2)), param => param[0] === param[1]), true)
]);

function f(source) {
  return Seq.join(Seq.map(Seq.pairAhead(Seq.fromArray(undefined, undefined, source.split(""))), param => param[0] + Option.getOr(param[1], "_")), ",");
}

let pairAheadTests = makeValueEqualTests("pairAhead", [
  [
    () => f(""),
    "",
    ""
  ],
  [
    () => f("a"),
    "a_",
    ""
  ],
  [
    () => f("ab"),
    "ab,b_",
    ""
  ],
  [
    () => f("abc"),
    "ab,bc,c_",
    ""
  ],
  [
    () => f("abcd"),
    "ab,bc,cd,d_",
    ""
  ]
]).concat([
  willNotThrow("pairAhead", "lazy", () => Seq.pairAhead(Seq.onceWith(throwIfInvoked))),
  valueEqual("pairAhead", "millions", () => Option.getExn(Seq.last(Seq.pairAhead(Seq.range(1, 999999))), undefined), [
    999999,
    undefined
  ]),
  seqEqual("pairAhead", "works with nested options", () => Seq.pairAhead(Seq.fromArray(undefined, undefined, [
    undefined,
    undefined
  ])), [
    [
      undefined,
      Primitive_option.some(undefined)
    ],
    [
      undefined,
      undefined
    ]
  ])
]);

function f$1(source) {
  return Seq.join(Seq.map(Seq.pairBehind(Seq.fromArray(undefined, undefined, source.split(""))), param => Option.getOr(param[0], "_") + param[1]), ",");
}

let pairBehindTests = makeValueEqualTests("pairBehind", [
  [
    () => f$1(""),
    "",
    ""
  ],
  [
    () => f$1("a"),
    "_a",
    ""
  ],
  [
    () => f$1("ab"),
    "_a,ab",
    ""
  ],
  [
    () => f$1("abc"),
    "_a,ab,bc",
    ""
  ],
  [
    () => f$1("abcd"),
    "_a,ab,bc,cd",
    ""
  ]
]).concat([
  willNotThrow("pairBehind", "lazy", () => Seq.pairBehind(Seq.onceWith(throwIfInvoked))),
  valueEqual("pairBehind", "millions", () => Option.getExn(Seq.last(Seq.pairBehind(Seq.range(1, 999999))), undefined), [
    999998,
    999999
  ]),
  seqEqual("pairBehind", "works with nested options", () => Seq.pairBehind(Seq.fromArray(undefined, undefined, [
    undefined,
    undefined
  ])), [
    [
      undefined,
      undefined
    ],
    [
      Primitive_option.some(undefined),
      undefined
    ]
  ])
]);

function f$2(source) {
  return Seq.join(Seq.map(Seq.neighbors(Seq.fromArray(undefined, undefined, source.split(""))), param => Option.getOr(param[0], "_") + param[1] + Option.getOr(param[2], "_")), ",");
}

let neighborsTests = makeValueEqualTests("neighbors", [
  [
    () => f$2(""),
    "",
    ""
  ],
  [
    () => f$2("a"),
    "_a_",
    ""
  ],
  [
    () => f$2("ab"),
    "_ab,ab_",
    ""
  ],
  [
    () => f$2("abc"),
    "_ab,abc,bc_",
    ""
  ],
  [
    () => f$2("abcd"),
    "_ab,abc,bcd,cd_",
    ""
  ]
]).concat([
  willNotThrow("neighbors", "lazy", () => Seq.neighbors(Seq.onceWith(throwIfInvoked))),
  valueEqual("neighbors", "millions", () => Option.getExn(Seq.last(Seq.neighbors(Seq.range(1, 999999))), undefined), [
    999998,
    999999,
    undefined
  ]),
  seqEqual("neighbors", "works with nested options", () => Seq.neighbors(Seq.fromArray(undefined, undefined, [
    undefined,
    undefined
  ])), [
    [
      undefined,
      undefined,
      Primitive_option.some(undefined)
    ],
    [
      Primitive_option.some(undefined),
      undefined,
      undefined
    ]
  ])
]);

let pairwiseTests = makeSeqEqualsTests("pairwise", [
  [
    Seq.pairwise(Seq.empty),
    [],
    ""
  ],
  [
    Seq.pairwise(Seq.once(1)),
    [],
    ""
  ],
  [
    Seq.pairwise(Seq.range(1, 2)),
    [[
        1,
        2
      ]],
    ""
  ],
  [
    Seq.pairwise(Seq.range(1, 5)),
    [
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        3,
        4
      ],
      [
        4,
        5
      ]
    ],
    ""
  ]
]).concat([willNotThrow("pairwise", "lazy", () => Seq.pairwise(Seq.onceWith(throwIfInvoked)))]);

let interleaveTests = makeSeqEqualsTests("interleave", [
  [
    Seq.interleave(Seq.empty, Seq.empty),
    [],
    ""
  ],
  [
    Seq.interleave(Seq.range(1, 3), Seq.range(4, 6)),
    [
      1,
      4,
      2,
      5,
      3,
      6
    ],
    ""
  ],
  [
    Seq.interleave(Seq.range(4, 7), Seq.once(1)),
    [
      4,
      1,
      5,
      6,
      7
    ],
    ""
  ],
  [
    Seq.interleave(Seq.once(1), Seq.range(4, 7)),
    [
      1,
      4,
      5,
      6,
      7
    ],
    ""
  ],
  [
    Seq.interleave(Seq.range(1, 3), Seq.range(4, 6)),
    [
      1,
      4,
      2,
      5,
      3,
      6
    ],
    ""
  ]
]);

let iterateTests = makeSeqEqualsTests("iterate", [
  [
    Seq.take(Seq.iterate(2, i => (i << 1)), 3),
    [
      2,
      4,
      8
    ],
    ""
  ],
  [
    Seq.take(Seq.iterate(2, i => (i << 1)), 1),
    [2],
    ""
  ],
  [
    Seq.take(Seq.iterate(2, i => (i << 1)), 0),
    [],
    ""
  ],
  [
    Seq.filter(Seq.take(Seq.iterate(1, i => i + 1 | 0), 999999), i => i === 999999),
    [999999],
    "millions"
  ]
]).concat([willNotThrow("iterate", "lazy", () => Seq.iterate(0, i => {
    Exn.raiseError("Boom!");
    return i;
  }))]);

function increment(max, seed) {
  let next = seed + 1 | 0;
  if (next <= max) {
    return next;
  }
  
}

let iterateWhileTests = makeSeqEqualsTests("iterateWhile", [
  [
    Seq.iterateWhile(4, __x => increment(10, __x)),
    [
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    ""
  ],
  [
    Seq.iterateWhile(9, __x => increment(10, __x)),
    [
      9,
      10
    ],
    ""
  ],
  [
    Seq.iterateWhile(10, __x => increment(10, __x)),
    [10],
    ""
  ],
  [
    Seq.iterateWhile(999, __x => increment(10, __x)),
    [999],
    "Always includes seed"
  ],
  [
    Seq.drop(Seq.iterateWhile(1, __x => increment(1000000, __x)), 999998),
    [
      999999,
      1000000
    ],
    ""
  ]
]).concat([willNotThrow("iterateWhile", "lazy", () => Seq.iterateWhile(0, i => {
    Exn.raiseError("Boom!");
    return i;
  }))]);

let basicTests = makeSeqEqualsTests("fromArray", [
  [
    Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.fromArray(undefined, undefined, [1]),
    [1],
    ""
  ],
  [
    Seq.fromArray(undefined, undefined, []),
    [],
    ""
  ],
  [
    Seq.fromArray(0, 2, [
      0,
      1,
      2,
      3
    ]),
    [
      0,
      1,
      2
    ],
    ""
  ],
  [
    Seq.fromArray(undefined, 2, [
      0,
      1,
      2,
      3
    ]),
    [
      0,
      1,
      2
    ],
    ""
  ],
  [
    Seq.fromArray(undefined, undefined, [
      0,
      1,
      2,
      3
    ]),
    [
      0,
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.fromArray(2, undefined, [
      0,
      1,
      2,
      3
    ]),
    [
      2,
      3
    ],
    ""
  ],
  [
    Seq.fromArray(2, 2, [
      0,
      1,
      2,
      3
    ]),
    [2],
    ""
  ],
  [
    Seq.fromArray(2, 1, [
      0,
      1,
      2,
      3
    ]),
    [
      2,
      1
    ],
    ""
  ]
]);

let throwsTests = [
  willThrow("fromArray", "throws", () => Seq.fromArray(-1, undefined, [
    1,
    2,
    3
  ])),
  willThrow("fromArray", "throws", () => Seq.fromArray(3, undefined, [
    1,
    2,
    3
  ])),
  willThrow("fromArray", "throws", () => Seq.fromArray(0, undefined, [])),
  willThrow("fromArray", "throws", () => Seq.fromArray(undefined, 0, [])),
  willThrow("fromArray", "throws", () => Seq.fromArray(undefined, -1, [
    1,
    2,
    3
  ])),
  willThrow("fromArray", "throws", () => Seq.fromArray(undefined, 3, [
    1,
    2,
    3
  ])),
  willThrow("fromArray", "throws", () => Seq.fromArray(undefined, 0, []))
];

let fromArrayTests = basicTests.concat(throwsTests);

let replicateTests = makeSeqEqualsTests("replicate", [
  [
    Seq.replicate("x", 0),
    [],
    ""
  ],
  [
    Seq.replicate("x", 1),
    ["x"],
    "x"
  ],
  [
    Seq.replicate("x", 2),
    [
      "x",
      "x"
    ],
    ""
  ],
  [
    Seq.replicate("x", 3),
    [
      "x",
      "x",
      "x"
    ],
    ""
  ]
]);

let replicateWithTests = makeSeqEqualsTests("replicateWith", [
  [
    Seq.replicateWith(() => "x", 0),
    [],
    ""
  ],
  [
    Seq.replicateWith(() => "x", 1),
    ["x"],
    "x"
  ],
  [
    Seq.replicateWith(() => "x", 2),
    [
      "x",
      "x"
    ],
    ""
  ],
  [
    Seq.replicateWith(() => "x", 3),
    [
      "x",
      "x",
      "x"
    ],
    ""
  ]
]);

let foreverTests = [valueEqual("forever", "millions", () => Seq.last(Seq.takeUntil(Seq.indexed(Seq.forever("x")), param => param[1] === 999999)), [
    "x",
    999999
  ])];

let takeTests = makeSeqEqualsTests("take", [
  [
    Seq.take(Seq.empty, 0),
    [],
    ""
  ],
  [
    Seq.take(Seq.empty, 1),
    [],
    ""
  ],
  [
    Seq.take(Seq.once(1), 0),
    [],
    ""
  ],
  [
    Seq.take(Seq.once(1), 1),
    [1],
    ""
  ],
  [
    Seq.take(Seq.once(1), 2),
    [1],
    ""
  ],
  [
    Seq.take(Seq.range(1, 5), 0),
    [],
    ""
  ],
  [
    Seq.take(Seq.range(1, 5), 1),
    [1],
    ""
  ],
  [
    Seq.take(Seq.range(1, 5), 3),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.take(Seq.range(1, 5), 5),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.take(Seq.range(1, 5), 6),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ]
]).concat([
  valueEqual("take", "millions", () => Seq.last(Seq.range(1, 999999)), 999999),
  willNotThrow("take", "lazy", () => Seq.take(Seq.onceWith(throwIfInvoked), 99)),
  willNotThrow("take", "if zero, do not iterate anything", () => Seq.consume(Seq.take(Seq.onceWith(throwIfInvoked), 0))),
  valueEqual("take", "if take 999_999, generator function called 999_999 times", () => {
    let callCount = {
      contents: 0
    };
    Seq.consume(Seq.take(Seq.foreverWith(() => {
      callCount.contents = callCount.contents + 1 | 0;
      return callCount.contents;
    }), 999999));
    return callCount.contents;
  }, 999999)
]);

let foreverWithTests = makeSeqEqualsTests("foreverWith", [
  [
    Seq.take(Seq.foreverWith(callCount()), 0),
    [],
    ""
  ],
  [
    Seq.take(Seq.foreverWith(callCount()), 1),
    [1],
    ""
  ],
  [
    Seq.take(Seq.foreverWith(callCount()), 5),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Option.getOr(Option.map(Seq.last(Seq.take(Seq.foreverWith(callCount()), 999999)), Seq.once), Seq.empty),
    [999999],
    ""
  ]
]).concat([willNotThrow("foreverWith", "lazy", () => Seq.foreverWith(throwIfInvoked))]);

let unfoldTests = makeSeqEqualsTests("unfold", [
  [
    Seq.unfold(1, i => {
      if (i <= 5) {
        return [
          i,
          i + 1 | 0
        ];
      }
      
    }),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.unfold(1, param => {}),
    [],
    "zero items"
  ],
  [
    Seq.unfold(1, i => {
      if (i < 100) {
        return [
          i,
          (i << 1)
        ];
      }
      
    }),
    [
      1,
      2,
      4,
      8,
      16,
      32,
      64
    ],
    ""
  ],
  [
    Seq.prepend(Seq.unfold([
      0,
      1
    ], param => {
      let b = param[1];
      let a = param[0];
      if ((a + b | 0) <= 100) {
        return [
          a + b | 0,
          [
            b,
            a + b | 0
          ]
        ];
      }
      
    }), Seq.fromArray(undefined, undefined, [
      0,
      1
    ])),
    [
      0,
      1,
      1,
      2,
      3,
      5,
      8,
      13,
      21,
      34,
      55,
      89
    ],
    "fibonacci"
  ]
]).concat([valueEqual("unfold", "millions", () => Seq.last(Seq.unfold(1, i => {
    if (i <= 999999) {
      return [
        i,
        i + 1 | 0
      ];
    }
    
  })), 999999)]);

function combos(s) {
  return Seq.map(Seq.indexed(Seq.fromArray(undefined, undefined, s.split(""))), param => [
    param[0],
    s.slice(param[1] + 1 | 0)
  ]);
}

function format(xxx) {
  return Seq.fromArray(undefined, undefined, Seq.toArray(Seq.map(xxx, xx => Seq.toArray(xx).join(""))));
}

let unfoldManyTests = makeSeqEqualsTests("unfoldMany", [
  [
    format(Seq.unfoldMany("abcd", combos)),
    [
      "abcd",
      "abd",
      "acd",
      "ad",
      "bcd",
      "bd",
      "cd",
      "d"
    ],
    ""
  ],
  [
    format(Seq.unfoldMany("abc", combos)),
    [
      "abc",
      "ac",
      "bc",
      "c"
    ],
    ""
  ],
  [
    format(Seq.unfoldMany("ab", combos)),
    [
      "ab",
      "b"
    ],
    ""
  ],
  [
    format(Seq.unfoldMany("a", combos)),
    ["a"],
    ""
  ],
  [
    format(Seq.unfoldMany("", combos)),
    [""],
    ""
  ],
  [
    Option.getExn(Option.map(Seq.last(Seq.unfoldMany("abcdefghijklmnopqrstuv", combos)), s => format(Seq.once(s))), undefined),
    ["v"],
    "millions"
  ]
]);

let initTests = makeSeqEqualsTests("init", [
  [
    Seq.init(1, inx => (inx << 1)),
    [0],
    ""
  ],
  [
    Seq.init(2, inx => (inx << 1)),
    [
      0,
      2
    ],
    ""
  ],
  [
    Seq.init(3, inx => (inx << 1)),
    [
      0,
      2,
      4
    ],
    ""
  ]
]).concat([
  valueEqual("init", "tens", () => Seq.last(Seq.init(100, inx => inx)), 99),
  valueEqual("init", "millions", () => Seq.last(Seq.range(0, 999999)), 999999)
]);

function process(xs, n) {
  return Seq.map(Seq.chunkBySize(xs, n), joinInts);
}

let chunkBySizeTests = makeSeqEqualsTests("chunkBySize", [
  [
    process(Seq.empty, 1),
    [],
    ""
  ],
  [
    process(Seq.once(1), 1),
    ["1"],
    ""
  ],
  [
    process(Seq.once(1), 2),
    ["1"],
    ""
  ],
  [
    process(Seq.range(1, 3), 1),
    [
      "1",
      "2",
      "3"
    ],
    ""
  ],
  [
    process(Seq.range(1, 3), 2),
    [
      "12",
      "3"
    ],
    ""
  ],
  [
    process(Seq.range(1, 3), 3),
    ["123"],
    ""
  ],
  [
    process(Seq.range(1, 3), 4),
    ["123"],
    "millions"
  ],
  [
    Option.getOr(Option.map(Seq.last(Seq.map(Seq.chunkBySize(Seq.take(Seq.cycle(Seq.range(0, 9)), 1000000), 10), joinInts)), Seq.once), Seq.once("")),
    ["0123456789"],
    ""
  ]
]).concat([
  willThrow("chunkBySize", "when size == 0", () => Seq.chunkBySize(Seq.range(1, 5), 0)),
  willThrow("chunkBySize", "when size == -1", () => Seq.chunkBySize(Seq.range(1, 5), 0)),
  willNotThrow("chunkBySize", "lazy", () => Seq.chunkBySize(Seq.onceWith(throwIfInvoked), 5))
]);

function push(sum, x) {
  let copied = sum.slice();
  copied.push(x);
  return copied;
}

function scanConcat(xs) {
  return Seq.map(Seq.scan(xs, [0], push), joinInts);
}

let scanTests = makeSeqEqualsTests("scan", [
  [
    scanConcat(Seq.range(1, 5)),
    [
      "0",
      "01",
      "012",
      "0123",
      "01234",
      "012345"
    ],
    ""
  ],
  [
    scanConcat(Seq.range(1, 2)),
    [
      "0",
      "01",
      "012"
    ],
    ""
  ],
  [
    scanConcat(Seq.once(1)),
    [
      "0",
      "01"
    ],
    ""
  ],
  [
    scanConcat(Seq.empty),
    ["0"],
    "always includes the zero"
  ],
  [
    Option.getOr(Option.map(Seq.last(Seq.map(Seq.scan(Seq.range(1, 999999), -1, (param, i) => i), __x => __x.toString())), Seq.once), Seq.once("")),
    ["999999"],
    ""
  ]
]);

let takeUntilTests = makeSeqEqualsTests("takeUntil", [
  [
    Seq.takeUntil(Seq.empty, trueAlways),
    [],
    ""
  ],
  [
    Seq.takeUntil(Seq.empty, falseAlways),
    [],
    ""
  ],
  [
    Seq.takeUntil(Seq.once(1), i => i === 1),
    [1],
    ""
  ],
  [
    Seq.takeUntil(Seq.once(1), falseAlways),
    [1],
    ""
  ],
  [
    Seq.takeUntil(Seq.once(1), trueAlways),
    [1],
    ""
  ],
  [
    Seq.takeUntil(Seq.range(1, 5), trueAlways),
    [1],
    ""
  ],
  [
    Seq.takeUntil(Seq.range(1, 5), falseAlways),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.takeUntil(Seq.range(1, 5), i => i === 3),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.takeUntil(Seq.range(1, 5), i => i === 1),
    [1],
    ""
  ],
  [
    Seq.takeUntil(Seq.range(1, 5), i => i === 5),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.takeUntil(Seq.fromArray(undefined, undefined, [
      1,
      2,
      2,
      2,
      3
    ]), i => i === 2),
    [
      1,
      2
    ],
    ""
  ],
  [
    Option.getOr(Option.map(Seq.last(Seq.takeUntil(Seq.range(1, 999999), i => i === 999999)), Seq.once), Seq.empty),
    [999999],
    "millions"
  ]
]);

let intersperseTests = makeSeqEqualsTests("intersperse", [
  [
    Seq.intersperse(Seq.fromArray(undefined, undefined, []), ","),
    [],
    ""
  ],
  [
    Seq.intersperse(Seq.fromArray(undefined, undefined, ["a"]), ","),
    ["a"],
    ""
  ],
  [
    Seq.intersperse(Seq.fromArray(undefined, undefined, [
      "a",
      "b"
    ]), ","),
    [
      "a",
      ",",
      "b"
    ],
    ""
  ],
  [
    Seq.intersperse(Seq.fromArray(undefined, undefined, [
      "a",
      "b",
      "c"
    ]), ","),
    [
      "a",
      ",",
      "b",
      ",",
      "c"
    ],
    ""
  ]
]);

function f$3() {
  return toDispenser(Seq.map(Seq.range(1, 100), __x => __x.toString()));
}

let intersperseWithTests = makeSeqEqualsTests("intersperseWith", [
  [
    Seq.intersperseWith(Seq.fromArray(undefined, undefined, []), f$3()),
    [],
    ""
  ],
  [
    Seq.intersperseWith(Seq.fromArray(undefined, undefined, ["a"]), f$3()),
    ["a"],
    ""
  ],
  [
    Seq.intersperseWith(Seq.fromArray(undefined, undefined, [
      "a",
      "b"
    ]), f$3()),
    [
      "a",
      "1",
      "b"
    ],
    ""
  ],
  [
    Seq.intersperseWith(Seq.fromArray(undefined, undefined, [
      "a",
      "b",
      "c"
    ]), f$3()),
    [
      "a",
      "1",
      "b",
      "2",
      "c"
    ],
    ""
  ]
]);

let dropWhileTests = [
  [
    Seq.empty,
    falseAlways,
    [],
    ""
  ],
  [
    Seq.empty,
    trueAlways,
    [],
    ""
  ],
  [
    Seq.once(1),
    i => i === 1,
    [],
    ""
  ],
  [
    Seq.once(1),
    falseAlways,
    [1],
    ""
  ],
  [
    Seq.once(1),
    trueAlways,
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    trueAlways,
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    falseAlways,
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i < 3,
    [
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i <= 5,
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i <= 1,
    [
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 99),
    i => i !== 99,
    [99],
    "tens"
  ],
  [
    Seq.range(1, 9999),
    i => i !== 9999,
    [9999],
    "thousands"
  ],
  [
    Seq.range(1, 999999),
    i => i !== 999999,
    [999999],
    "millions"
  ]
].map((param, inx) => {
  let predicate = param[1];
  let source = param[0];
  return seqEqual("dropWhile", "index " + inx.toString() + " " + param[3], () => Seq.dropWhile(source, predicate), param[2]);
});

let filterSomeTests = makeSeqEqualsTests("filterSome", [
  [
    Seq.filterSome(Seq.empty),
    [],
    ""
  ],
  [
    Seq.filterSome(Seq.once(undefined)),
    [],
    ""
  ],
  [
    Seq.filterSome(Seq.once(1)),
    [1],
    ""
  ],
  [
    Seq.filterSome(Seq.fromArray(undefined, undefined, [
      1,
      undefined,
      3,
      undefined
    ])),
    [
      1,
      3
    ],
    ""
  ]
]);

let filterOkTests = makeSeqEqualsTests("filterOk", [
  [
    Seq.filterOk(Seq.empty),
    [],
    ""
  ],
  [
    Seq.filterOk(Seq.once({
      TAG: "Error",
      _0: "x"
    })),
    [],
    ""
  ],
  [
    Seq.filterOk(Seq.once({
      TAG: "Ok",
      _0: 1
    })),
    [1],
    ""
  ],
  [
    Seq.filterOk(Seq.fromArray(undefined, undefined, [
      {
        TAG: "Ok",
        _0: 1
      },
      {
        TAG: "Error",
        _0: "x"
      },
      {
        TAG: "Ok",
        _0: 3
      },
      {
        TAG: "Error",
        _0: "x"
      }
    ])),
    [
      1,
      3
    ],
    ""
  ]
]);

let items = [
  1,
  undefined,
  Primitive_option.some(undefined),
  2,
  undefined,
  Primitive_option.some(undefined)
];

let filterMapTests = [
  [
    Seq.empty,
    param => 1,
    [],
    ""
  ],
  [
    Seq.empty,
    param => {},
    [],
    ""
  ],
  [
    Seq.once(1),
    i => (i << 1),
    [2],
    ""
  ],
  [
    Seq.once(1),
    param => {},
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i,
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    param => {},
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    i => {
      if (i === 3 || i === 5) {
        return i;
      }
      
    },
    [
      3,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    i => {
      if (i === 5) {
        return 99;
      }
      
    },
    [99],
    ""
  ],
  [
    Seq.range(1, 5),
    i => {
      if (i === 1 || i === 3) {
        return (i << 1);
      }
      
    },
    [
      2,
      6
    ],
    ""
  ],
  [
    Seq.range(1, 999999),
    i => {
      if (i === 999999) {
        return -i | 0;
      }
      
    },
    [-999999],
    "millions"
  ]
].map((param, inx) => {
  let f = param[1];
  let source = param[0];
  return seqEqual("filterMap", "index " + inx.toString() + " " + param[3], () => Seq.filterMap(source, f), param[2]);
}).concat([valueEqual("filterMap", "option of options yields correct values", () => Seq.equals(Seq.filterMap(Seq.fromArray(undefined, undefined, items), i => i), Seq.fromArray(undefined, undefined, [
    1,
    undefined,
    2,
    undefined
  ]), (a, b) => Option.compare(a, b, Primitive_int.compare) === 0.0), true)]);

let items$1 = [
  1,
  undefined,
  Primitive_option.some(undefined),
  2,
  undefined,
  Primitive_option.some(undefined)
];

let filterMapiTests = makeSeqEqualsTests("filterMapi", [
  [
    Seq.filterMapi(Seq.range(1, 3), (num, inx) => {
      if (num === 2 && inx === 1) {
        return num;
      }
      
    }),
    [2],
    ""
  ],
  [
    Seq.filterMapi(Seq.range(1, 3), (param, inx) => inx),
    [
      0,
      1,
      2
    ],
    ""
  ],
  [
    Seq.filterMapi(Seq.empty, (param, inx) => inx),
    [],
    ""
  ],
  [
    Seq.filterMapi(Seq.range(1, 999999), (num, inx) => {
      if (num === 999999) {
        return inx;
      }
      
    }),
    [999998],
    ""
  ]
]).concat([valueEqual("filterMapi", "option of options yields correct values", () => Seq.equals(Seq.filterMapi(Seq.fromArray(undefined, undefined, items$1), (value, _inx) => value), Seq.fromArray(undefined, undefined, [
    1,
    undefined,
    2,
    undefined
  ]), (a, b) => Option.compare(a, b, Primitive_int.compare) === 0.0), true)]);

let filterTests = [
  [
    Seq.empty,
    falseAlways,
    [],
    ""
  ],
  [
    Seq.empty,
    trueAlways,
    [],
    ""
  ],
  [
    Seq.once(1),
    i => i === 1,
    [1],
    ""
  ],
  [
    Seq.once(1),
    falseAlways,
    [],
    ""
  ],
  [
    Seq.once(1),
    trueAlways,
    [1],
    ""
  ],
  [
    Seq.range(1, 5),
    trueAlways,
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    falseAlways,
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    i => {
      if (i === 3) {
        return true;
      } else {
        return i === 5;
      }
    },
    [
      3,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i === 5,
    [5],
    ""
  ],
  [
    Seq.range(1, 5),
    i => {
      if (i === 1) {
        return true;
      } else {
        return i === 3;
      }
    },
    [
      1,
      3
    ],
    ""
  ],
  [
    Seq.range(1, 999999),
    i => i === 999999,
    [999999],
    "millions"
  ]
].map((param, inx) => {
  let predicate = param[1];
  let source = param[0];
  return seqEqual("filter", "index " + inx.toString() + " " + param[3], () => Seq.filter(source, predicate), param[2]);
}).concat([
  seqEqual("filteri", "", () => Seq.filteri(Seq.range(1, 5), (n, inx) => {
    if (n === 3) {
      return inx === 2;
    } else {
      return false;
    }
  }), [3]),
  seqEqual("filteri", "when skipping millions => no stack problem", () => Seq.filteri(Seq.concat(Seq.replicate(1, 999999), Seq.once(2)), (value, param) => value !== 1), [2])
]);

let dropUntilTests = [
  [
    Seq.empty,
    falseAlways,
    [],
    ""
  ],
  [
    Seq.empty,
    trueAlways,
    [],
    ""
  ],
  [
    Seq.once(1),
    i => i === 1,
    [1],
    ""
  ],
  [
    Seq.once(1),
    falseAlways,
    [],
    ""
  ],
  [
    Seq.once(1),
    trueAlways,
    [1],
    ""
  ],
  [
    Seq.range(1, 5),
    trueAlways,
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    falseAlways,
    [],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i === 3,
    [
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i === 5,
    [5],
    ""
  ],
  [
    Seq.range(1, 5),
    i => i === 1,
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.range(1, 999999),
    i => i === 999999,
    [999999],
    "millions"
  ]
].map((param, inx) => {
  let predicate = param[1];
  let source = param[0];
  return seqEqual("dropUntil", "index " + inx.toString() + " " + param[3], () => Seq.dropUntil(source, predicate), param[2]);
});

let forEachTests = [
  valueEqual("forEach", "every value is enumerated", () => {
    let result = [];
    Seq.forEach(Seq.range(1, 5), i => {
      result.push(i);
    });
    return result;
  }, [
    1,
    2,
    3,
    4,
    5
  ]),
  valueEqual("forEach", "millions", () => {
    let lastSeen = {
      contents: undefined
    };
    Seq.forEach(Seq.range(1, 999999), i => {
      lastSeen.contents = i;
    });
    return lastSeen.contents;
  }, 999999),
  valueEqual("forEach", "empty", () => {
    let lastSeen = {
      contents: undefined
    };
    Seq.forEach(Seq.empty, i => {
      lastSeen.contents = Primitive_option.some(i);
    });
    return lastSeen.contents;
  }, undefined),
  valueEqual("forEachi", "", () => {
    let result = [];
    Seq.forEachi(Seq.range(1, 5), (n, inx) => {
      result.push([
        n,
        inx
      ]);
    });
    return result;
  }, [
    [
      1,
      0
    ],
    [
      2,
      1
    ],
    [
      3,
      2
    ],
    [
      4,
      3
    ],
    [
      5,
      4
    ]
  ])
];

let someTests = makeValueEqualTests("some", [
  [
    () => Seq.some(Seq.empty, param => true),
    false,
    "if empty is false"
  ],
  [
    () => Seq.some(Seq.empty, param => false),
    false,
    "if empty is false"
  ],
  [
    () => Seq.some(Seq.range(1, 3), i => i === 2),
    true,
    ""
  ],
  [
    () => Seq.some(Seq.range(1, 3), param => false),
    false,
    ""
  ],
  [
    () => Seq.some(Seq.range(1, 999999), i => i === 999999),
    true,
    "millions"
  ]
]);

let everyTests = makeValueEqualTests("every", [
  [
    () => Seq.every(Seq.empty, param => true),
    true,
    "if empty is true"
  ],
  [
    () => Seq.every(Seq.empty, param => false),
    true,
    "if empty is true"
  ],
  [
    () => Seq.every(Seq.range(1, 3), i => i >= 1),
    true,
    ""
  ],
  [
    () => Seq.every(Seq.range(1, 3), param => false),
    false,
    ""
  ],
  [
    () => Seq.every(Seq.range(1, 999999), param => true),
    true,
    "millions"
  ]
]);

let findMapLastTests = makeValueEqualTests("findMapLast", [
  [
    () => Seq.findMapLast(Seq.range(1, 6), i => {
      if (i < 4) {
        return (i << 1);
      }
      
    }),
    6,
    ""
  ],
  [
    () => Seq.findMapLast(Seq.range(1, 6), i => {
      if (i < 7) {
        return (i << 1);
      }
      
    }),
    12,
    ""
  ],
  [
    () => Seq.findMapLast(Seq.range(1, 6), i => {
      if (i < 2) {
        return i + 10 | 0;
      }
      
    }),
    11,
    ""
  ],
  [
    () => Seq.findMapLast(Seq.range(1, 6), param => {}),
    undefined,
    ""
  ],
  [
    () => Seq.findMapLast(Seq.range(1, 999999), i => {
      if (i === 999999) {
        return 1000000;
      }
      
    }),
    1000000,
    ""
  ]
]);

let findMapTests = makeValueEqualTests("findMap", [
  [
    () => Seq.findMap(Seq.range(1, 5), i => {
      if (i === 2) {
        return "x";
      }
      
    }),
    "x",
    "if found, some"
  ],
  [
    () => Seq.findMap(Seq.range(1, 5), param => {}),
    undefined,
    "if not found, none"
  ],
  [
    () => Seq.findMap(Seq.range(1, 99999), i => {
      if (i === 99999) {
        return "x";
      }
      
    }),
    "x",
    "big"
  ]
]).concat([
  valueEqual("findMap", "nested options - find Some(Some(_))", () => Option.getExn(Seq.findMap(Seq.fromArray(undefined, undefined, [
    undefined,
    1,
    Primitive_option.some(undefined)
  ]), i => i), undefined), 1),
  valueEqual("findMap", "nested options - find Some(None)", () => Option.getExn(Seq.findMap(Seq.fromArray(undefined, undefined, [
    Primitive_option.some(undefined),
    undefined,
    1,
    Primitive_option.some(undefined)
  ]), i => i), undefined), undefined),
  valueEqual("findMap", "nested options - find Some(None) (must return as Some(Some(None)))", () => Option.getExn(Seq.findMap(Seq.fromArray(undefined, undefined, [
    1,
    undefined,
    Primitive_option.some(undefined)
  ]), i => {
    if (i !== undefined && Primitive_option.valFromOption(i) === undefined) {
      return Primitive_option.some(Primitive_option.some(undefined));
    }
    
  }), undefined), Primitive_option.some(undefined)),
  valueEqual("findMap", "nested options - find None", () => Option.getExn(Seq.findMap(Seq.fromArray(undefined, undefined, [
    1,
    undefined,
    Primitive_option.some(undefined)
  ]), i => {
    if (Option.isNone(i)) {
      return Primitive_option.some(undefined);
    }
    
  }), undefined), undefined)
]);

let toArrayTests = [valueEqual("toArray", "when empty sequence, no generator functions are called", () => {
    let calls = {
      contents: 0
    };
    Seq.toArray(Seq.take(Seq.unfold(0, i => {
      calls.contents = calls.contents + 1 | 0;
      if (i < 100) {
        return [
          i,
          i + 1 | 0
        ];
      }
      
    }), 0));
    return calls.contents;
  }, 0)];

let lengthTests = [
  valueEqual("length", "if empty => 0", () => Seq.length(Seq.empty), 0),
  valueEqual("length", "if not empty", () => Seq.length(Seq.range(1, 5)), 5),
  valueEqual("length", "millions", () => Seq.length(Seq.replicate(1, 999999)), 999999)
];

let equalsTests = [
  [
    "",
    "",
    true
  ],
  [
    "",
    "a",
    false
  ],
  [
    "a",
    "",
    false
  ],
  [
    "a",
    "a",
    true
  ],
  [
    "a",
    "aa",
    false
  ],
  [
    "aa",
    "a",
    false
  ],
  [
    "aa",
    "aa",
    true
  ],
  [
    "aa",
    "aaa",
    false
  ]
].map(param => {
  let expected = param[2];
  let ys = param[1];
  let xs = param[0];
  return valueEqual("equals", xs + "," + ys + " => " + (
    expected ? "true" : "false"
  ), () => {
    let xs$1 = characters(xs);
    let ys$1 = characters(ys);
    return Seq.equals(xs$1, ys$1, (i, j) => i === j);
  }, expected);
});

let compareTests = [
  [
    "",
    "",
    0
  ],
  [
    "",
    "a",
    -1
  ],
  [
    "a",
    "",
    1
  ],
  [
    "a",
    "a",
    0
  ],
  [
    "a",
    "aa",
    -1
  ],
  [
    "aa",
    "a",
    1
  ],
  [
    "aa",
    "aa",
    0
  ],
  [
    "aa",
    "aaa",
    -1
  ]
].map(param => {
  let expected = param[2];
  let ys = param[1];
  let xs = param[0];
  return valueEqual("compare", xs + "," + ys + " => " + expected.toString(), () => {
    let xs$1 = characters(xs);
    let ys$1 = characters(ys);
    return Seq.compare(xs$1, ys$1, (prim0, prim1) => prim0.localeCompare(prim1));
  }, expected);
});

let unconsTests = [
  valueEqual("uncons", "when empty => None", () => Seq.uncons(Seq.empty), undefined),
  valueEqual("uncons", "when once => Some(head,empty)", () => Option.map(Seq.uncons(Seq.once(4)), param => [
    param[0],
    Seq.toArray(param[1])
  ]), [
    4,
    []
  ]),
  valueEqual("uncons", "when many items => Some(head,tail)", () => Option.map(Seq.uncons(Seq.fromArray(undefined, undefined, [
    1,
    2,
    3
  ])), param => [
    param[0],
    Seq.toArray(param[1])
  ]), [
    1,
    [
      2,
      3
    ]
  ])
];

let tailTests = [
  willNotThrow("tail", "lazy", () => Seq.tail(Seq.onceWith(throwIfInvoked))),
  seqEqual("tail", "if empty => empty", () => Seq.tail(Seq.empty), []),
  seqEqual("tail", "if singleton => empty", () => Seq.tail(Seq.once(1)), []),
  seqEqual("tail", "if many => get tail", () => Seq.tail(Seq.range(1, 5)), [
    2,
    3,
    4,
    5
  ])
];

let headTests = [
  valueEqual("head", "when empty", () => Seq.head(Seq.empty), undefined),
  valueEqual("head", "when not empty", () => Seq.head(Seq.range(1, 5)), 1)
];

let minByMaxByTests = [
  valueEqual("minBy", "when no items => None", () => Seq.minBy(Seq.empty, Primitive_int.compare), undefined),
  valueEqual("minBy", "when items => Some", () => Seq.minBy(Seq.fromArray(undefined, undefined, [
    6,
    7,
    8,
    3,
    1,
    3,
    5,
    8
  ]), Primitive_int.compare), 1),
  valueEqual("maxBy", "when no items => None", () => Seq.maxBy(Seq.empty, Primitive_int.compare), undefined),
  valueEqual("maxBy", "when items => Some", () => Seq.maxBy(Seq.fromArray(undefined, undefined, [
    6,
    7,
    8,
    3,
    1,
    3,
    5,
    7
  ]), Primitive_int.compare), 8)
];

let isEmptyTests = [
  valueEqual("isEmpty", "when empty => true", () => Seq.isEmpty(Seq.empty), true),
  valueEqual("isEmpty", "when not empty => false", () => Seq.isEmpty(Seq.once(2)), false)
];

let joinTests = makeValueEqualTests("join", [
  [
    () => Seq.join(Seq.empty, ""),
    "",
    "empty source"
  ],
  [
    () => Seq.join(Seq.empty, ","),
    "",
    "empty source"
  ],
  [
    () => Seq.join(Seq.once("x"), ""),
    "x",
    "singleton source"
  ],
  [
    () => Seq.join(Seq.once("x"), ","),
    "x",
    "singleton source"
  ],
  [
    () => Seq.join(Seq.fromArray(undefined, undefined, [
      "a",
      "b"
    ]), ""),
    "ab",
    "two items in source"
  ],
  [
    () => Seq.join(Seq.fromArray(undefined, undefined, [
      "a",
      "b"
    ]), ","),
    "a,b",
    "two items in source"
  ],
  [
    () => Seq.join(Seq.fromArray(undefined, undefined, [
      "a",
      "b",
      "c",
      "d"
    ]), ""),
    "abcd",
    "many items in source"
  ],
  [
    () => Seq.join(Seq.fromArray(undefined, undefined, [
      "a",
      "b",
      "c",
      "d"
    ]), ","),
    "a,b,c,d",
    "many items in source"
  ]
]);

let exactlyOneTests = makeValueEqualTests("exactlyOne", [
  [
    () => Seq.exactlyOne(Seq.empty),
    undefined,
    ""
  ],
  [
    () => Seq.exactlyOne(Seq.once(1)),
    1,
    ""
  ],
  [
    () => Seq.exactlyOne(Seq.range(1, 2)),
    undefined,
    ""
  ]
]);

let isSortedByTests = makeValueEqualTests("isSortedBy", [
  [
    () => Seq.isSortedBy(Seq.empty, Primitive_int.compare),
    true,
    ""
  ],
  [
    () => Seq.isSortedBy(Seq.once(3), Primitive_int.compare),
    true,
    ""
  ],
  [
    () => Seq.isSortedBy(Seq.fromArray(undefined, undefined, [
      1,
      4,
      4,
      6,
      7,
      8,
      9,
      10
    ]), Primitive_int.compare),
    true,
    ""
  ],
  [
    () => Seq.isSortedBy(Seq.fromArray(undefined, undefined, [
      1,
      4,
      4,
      6,
      7,
      8,
      0,
      10
    ]), Primitive_int.compare),
    false,
    ""
  ]
]);

let toOptionTests = [
  valueEqual("toOption", "when empty => None", () => Seq.toOption(Seq.empty), undefined),
  valueEqual("toOption", "when once => Some", () => Seq.toArray(Option.getOr(Seq.toOption(Seq.once(1)), Seq.empty)), [1]),
  valueEqual("toOption", "when many items => Some", () => Seq.toArray(Option.getOr(Seq.toOption(Seq.range(1, 3)), Seq.empty)), [
    1,
    2,
    3
  ])
];

function add(total, x) {
  return total + x | 0;
}

function lastSeen(param, x) {
  return x;
}

let reduceTests = [
  [
    () => Seq.reduce(Seq.empty, -1, add),
    -1
  ],
  [
    () => Seq.reduce(Seq.once(99), 1, add),
    100
  ],
  [
    () => Seq.reduce(Seq.range(1, 3), 1, add),
    7
  ],
  [
    () => Option.getOr(Seq.reduce(Seq.range(1, 99), undefined, lastSeen), -1),
    99
  ],
  [
    () => Option.getOr(Seq.reduce(Seq.range(1, 9999), undefined, lastSeen), -1),
    9999
  ],
  [
    () => Option.getOr(Seq.reduce(Seq.range(1, 999999), undefined, lastSeen), -1),
    999999
  ]
].map((param, index) => valueEqual("reduce", "index " + index.toString(), param[0], param[1]));

function add$1(total, x) {
  return total + x | 0;
}

function throwIfTryToAdd(total, x) {
  Exn.raiseError("Tried to invoke a testing function that always fails.");
  return total + x | 0;
}

let reduceUntilTests = makeValueEqualTests("reduceUntil", [
  [
    () => Seq.reduceUntil(Seq.empty, 100, add$1, param => false),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.empty, 100, add$1, param => true),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.empty, 100, throwIfTryToAdd, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.onceWith(throwIfInvoked), 100, add$1, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.once(1), 100, add$1, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.once(1), 100, add$1, param => false),
    101,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 2), 100, add$1, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 2), 100, add$1, i => i >= 101),
    101,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 2), 100, add$1, i => i >= 103),
    103,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 2), 100, add$1, param => false),
    103,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 3), 100, add$1, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 3), 100, add$1, i => i >= 101),
    101,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 3), 100, add$1, i => i >= 103),
    103,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 3), 100, add$1, i => i >= 106),
    106,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 3), 100, add$1, param => false),
    106,
    ""
  ],
  [
    () => Seq.reduceUntil(Seq.range(1, 999999), 0, (param, i) => i, param => false),
    999999,
    "millions"
  ]
]);

function add$2(total, x) {
  return total + x | 0;
}

function throwIfTryToAdd$1(total, x) {
  Exn.raiseError("Tried to invoke a testing function that always fails.");
  return total + x | 0;
}

let reduceWhileTests = makeValueEqualTests("reduceWhile", [
  [
    () => Seq.reduceWhile(Seq.empty, 100, add$2, param => false),
    undefined,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.once(1), 100, add$2, param => false),
    undefined,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 2), 100, add$2, param => false),
    undefined,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 3), 100, add$2, param => false),
    undefined,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.onceWith(throwIfInvoked), 100, add$2, param => false),
    undefined,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.empty, 100, add$2, param => true),
    100,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.empty, 100, throwIfTryToAdd$1, param => true),
    100,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.once(1), 100, add$2, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.once(1), 100, add$2, i => i <= 101),
    101,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 2), 100, add$2, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 2), 100, add$2, i => i <= 101),
    101,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 2), 100, add$2, i => i <= 103),
    103,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 3), 100, add$2, i => i === 100),
    100,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 3), 100, add$2, i => i <= 101),
    101,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 3), 100, add$2, i => i <= 103),
    103,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 3), 100, add$2, i => i <= 106),
    106,
    ""
  ],
  [
    () => Seq.reduceWhile(Seq.range(1, 999999), 0, (param, i) => i, i => i <= 999998),
    999998,
    "millions"
  ]
]);

function add$3(sum, x) {
  return sum + x | 0;
}

function lastSeen$1(param, x) {
  return x;
}

let sumTests = makeValueEqualTests("sum", [
  [
    () => Seq.sumBy(Seq.empty, add$3),
    undefined,
    ""
  ],
  [
    () => Seq.sumBy(Seq.once(99), add$3),
    99,
    ""
  ],
  [
    () => Seq.sumBy(Seq.range(1, 2), add$3),
    3,
    ""
  ],
  [
    () => Seq.sumBy(Seq.range(1, 4), add$3),
    10,
    ""
  ],
  [
    () => Seq.sumBy(Seq.range(1, 9999), lastSeen$1),
    9999,
    ""
  ],
  [
    () => Seq.sumBy(Seq.range(1, 999999), lastSeen$1),
    999999,
    ""
  ]
]);

function add$4(sum, x) {
  return sum + x | 0;
}

let prefixSumTests = makeSeqEqualsTests("prefixSum", [
  [
    Seq.prefixSum(Seq.fromArray(undefined, undefined, []), add$4),
    [],
    ""
  ],
  [
    Seq.prefixSum(Seq.fromArray(undefined, undefined, [1]), add$4),
    [1],
    ""
  ],
  [
    Seq.prefixSum(Seq.fromArray(undefined, undefined, [
      1,
      2
    ]), add$4),
    [
      1,
      3
    ],
    ""
  ],
  [
    Seq.prefixSum(Seq.fromArray(undefined, undefined, [
      1,
      2,
      3,
      4,
      5
    ]), add$4),
    [
      1,
      3,
      6,
      10,
      15
    ],
    ""
  ]
]).concat([
  valueEqual("prefixSum", "millions", () => Seq.last(Seq.prefixSum(Seq.range(1, 999999), (param, n) => n)), 999999),
  willNotThrow("prefixSum", "lazy", () => Seq.prefixSum(Seq.onceWith(throwIfInvoked), add$4))
]);

let lastTests = [
  [
    Seq.empty,
    undefined
  ],
  [
    Seq.once(1),
    1
  ],
  [
    Seq.range(1, 9),
    9
  ],
  [
    Seq.range(1, 99),
    99
  ],
  [
    Seq.range(1, 999),
    999
  ],
  [
    Seq.range(1, 999999),
    999999
  ]
].map((param, index) => {
  let xs = param[0];
  return valueEqual("last", "index " + index.toString(), () => Seq.last(xs), param[1]);
});

let atTests = [
  [
    [
      Seq.empty,
      -1
    ],
    undefined
  ],
  [
    [
      Seq.empty,
      0
    ],
    undefined
  ],
  [
    [
      Seq.empty,
      1
    ],
    undefined
  ],
  [
    [
      Seq.once(1),
      -1
    ],
    undefined
  ],
  [
    [
      Seq.once(1),
      0
    ],
    1
  ],
  [
    [
      Seq.once(1),
      1
    ],
    undefined
  ],
  [
    [
      Seq.range(0, 9),
      0
    ],
    0
  ],
  [
    [
      Seq.range(0, 9),
      1
    ],
    1
  ],
  [
    [
      Seq.range(0, 9),
      9
    ],
    9
  ],
  [
    [
      Seq.range(0, 9),
      10
    ],
    undefined
  ],
  [
    [
      Seq.range(0, 999999),
      9999
    ],
    9999
  ]
].map((param, index) => {
  let match = param[0];
  let inx = match[1];
  let xs = match[0];
  return valueEqual("at", "index " + index.toString(), () => Seq.at(xs, inx), param[1]);
});

let validationTests = [
  [
    "when empty, return empty",
    [],
    {
      TAG: "Ok",
      _0: []
    }
  ],
  [
    "when one error, return it",
    [30],
    {
      TAG: "Error",
      _0: "30"
    }
  ],
  [
    "when one ok, return it",
    [2],
    {
      TAG: "Ok",
      _0: [4]
    }
  ],
  [
    "when all ok, return all",
    [
      1,
      2,
      3
    ],
    {
      TAG: "Ok",
      _0: [
        2,
        4,
        6
      ]
    }
  ],
  [
    "when all error, return first",
    [
      20,
      30,
      40
    ],
    {
      TAG: "Error",
      _0: "20"
    }
  ],
  [
    "when mix, return first error",
    [
      1,
      2,
      14,
      3,
      4
    ],
    {
      TAG: "Error",
      _0: "14"
    }
  ]
];

function validate(n) {
  if (n < 10) {
    return {
      TAG: "Ok",
      _0: (n << 1)
    };
  } else {
    return {
      TAG: "Error",
      _0: n.toString()
    };
  }
}

let everyOkTests = validationTests.map(param => {
  let input = param[1];
  return valueEqual("everyOk", param[0], () => Result.map(Seq.everyOk(Seq.map(Seq.fromArray(undefined, undefined, input), validate)), Seq.toArray), param[2]);
});

let everySomeTests = validationTests.map(param => {
  let input = param[1];
  return valueEqual("everySome", param[0], () => Option.map(Seq.everySome(Seq.map(Seq.map(Seq.fromArray(undefined, undefined, input), validate), Seq__Result.toOption)), Seq.toArray), Seq__Result.toOption(param[2]));
});

let memoizeTests = [
  Seq__Test.fromPredicate("Seq", "cache", "calculations only done once", () => {
    let randoms = Seq.cache(Seq.take(Seq.foreverWith(() => Math.random()), 4));
    let nums1 = Seq.toArray(randoms);
    let nums2 = Seq.toArray(randoms);
    let nums3 = Seq.toArray(randoms);
    if (Primitive_object.equal(nums1, nums2)) {
      return Primitive_object.equal(nums2, nums3);
    } else {
      return false;
    }
  }),
  Seq__Test.fromPredicate("Seq", "cache", "all lazy; can cache foreverWith", () => {
    let randoms = Seq.take(Seq.cache(Seq.foreverWith(() => Math.random())), 4);
    let nums1 = Seq.toArray(randoms);
    let nums2 = Seq.toArray(randoms);
    let nums3 = Seq.toArray(randoms);
    if (Primitive_object.equal(nums1, nums2)) {
      return Primitive_object.equal(nums2, nums3);
    } else {
      return false;
    }
  })
];

let findTests = [
  [
    () => Seq.empty,
    param => true,
    undefined,
    "when empty and predicate true"
  ],
  [
    () => Seq.empty,
    param => false,
    undefined,
    "when empty and predicate false"
  ],
  [
    () => Seq.once(1),
    i => i === 1,
    1,
    "when once and found"
  ],
  [
    () => Seq.once(1),
    param => false,
    undefined,
    "when once and predicate false"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    i => i === 1,
    1,
    "when many and is first"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    i => i === 2,
    2,
    "when many and is middle"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    i => i === 3,
    3,
    "when many and is last"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    param => false,
    undefined,
    "when many and predicate false"
  ],
  [
    () => Seq.range(1, 999999),
    i => i === 999999,
    999999,
    "when million"
  ],
  [
    () => Seq.range(1, 999999),
    param => false,
    undefined,
    "when million"
  ]
].map((param, index) => {
  let result = param[2];
  let predicate = param[1];
  let source = param[0];
  return Seq__Test.fromPredicate("Seq", "find", index.toString() + " " + param[3], () => Primitive_object.equal(Seq.find(source(), predicate), result));
});

let findLastTests = [
  [
    () => Seq.empty,
    param => true,
    undefined,
    "when empty and predicate true"
  ],
  [
    () => Seq.empty,
    param => false,
    undefined,
    "when empty and predicate false"
  ],
  [
    () => Seq.once(1),
    i => i === 1,
    1,
    "when once and found"
  ],
  [
    () => Seq.once(1),
    param => false,
    undefined,
    "when once and predicate false"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3,
      4,
      5,
      6
    ]),
    i => i % 2 === 0,
    6,
    "when many and is last"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3,
      4
    ]),
    i => i % 2 === 1,
    3,
    "when many and is in middle"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    i => i === 1,
    1,
    "when many and is last"
  ],
  [
    () => Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ]),
    param => false,
    undefined,
    "when many and predicate false"
  ],
  [
    () => Seq.range(1, 999999),
    i => i === 999999,
    999999,
    "when million"
  ],
  [
    () => Seq.range(1, 999999),
    param => false,
    undefined,
    "when million"
  ]
].map((param, index) => {
  let result = param[2];
  let predicate = param[1];
  let source = param[0];
  return Seq__Test.fromPredicate("Seq", "findLast", index.toString() + " " + param[3], () => Primitive_object.equal(Seq.findLast(source(), predicate), result));
});

function test(xs, ys, expected) {
  return Seq__Test.fromPredicate("Seq", "map2", xs + "," + ys + " => " + expected, () => {
    let xs$1 = characters(xs);
    let ys$1 = characters(ys);
    let expected$1 = expected === "" ? Seq.empty : Seq.fromArray(undefined, undefined, expected.split(","));
    let actual = Seq.map2(xs$1, ys$1, (x, y) => x + y);
    return Seq.equals(expected$1, actual, (i, j) => i === j);
  });
}

let map2Tests = [
  test("", "", ""),
  test("a", "", ""),
  test("", "a", ""),
  test("a", "b", "ab"),
  test("aa", "bb", "ab,ab"),
  test("aaa", "bbb", "ab,ab,ab"),
  test("a", "bbb", "ab"),
  test("aaa", "b", "ab"),
  test("aaaaaaa", "bbb", "ab,ab,ab")
];

function test$1(xs, ys, zs, expected) {
  return Seq__Test.fromPredicate("Seq", "map3", xs + "," + ys + "," + zs + " => " + expected, () => {
    let xs$1 = characters(xs);
    let ys$1 = characters(ys);
    let zs$1 = characters(zs);
    let expected$1 = expected === "" ? Seq.empty : Seq.fromArray(undefined, undefined, expected.split(","));
    let actual = Seq.map3(xs$1, ys$1, zs$1, (x, y, z) => x + y + z);
    return Seq.equals(expected$1, actual, (i, j) => i === j);
  });
}

let map3Tests = [
  test$1("", "", "", ""),
  test$1("a", "", "", ""),
  test$1("", "b", "", ""),
  test$1("", "", "c", ""),
  test$1("a", "", "c", ""),
  test$1("a", "b", "c", "abc"),
  test$1("a", "bb", "ccc", "abc"),
  test$1("aa", "bb", "ccc", "abc,abc"),
  test$1("aaaaaaaa", "bbb", "c", "abc"),
  test$1("aaaaaaaa", "bbbbbb", "ccc", "abc,abc,abc")
];

let consumeTests = [Seq__Test.fromPredicate("Seq", "consume", "enumerates sequence for side effects", () => {
    let lastSeen = {
      contents: 0
    };
    Seq.consume(Seq.tap(Seq.range(0, 999999), i => {
      lastSeen.contents = i;
    }));
    return lastSeen.contents === 999999;
  })];

let reverseTests = makeSeqEqualsTests("reverse", [
  [
    Seq.reverse(Seq.empty),
    [],
    ""
  ],
  [
    Seq.reverse(Seq.once(1)),
    [1],
    ""
  ],
  [
    Seq.reverse(Seq.range(1, 5)),
    [
      5,
      4,
      3,
      2,
      1
    ],
    ""
  ]
]).concat([willNotThrow("reverse", "lazy; not reversed until iterated", () => Seq.reverse(Seq.onceWith(throwIfInvoked)))]);

let orElseTests = makeSeqEqualsTests("orElse", [
  [
    Seq.orElse(Seq.empty, Seq.empty),
    [],
    ""
  ],
  [
    Seq.orElse(Seq.empty, Seq.range(1, 3)),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq.orElse(Seq.once(1), Seq.range(4, 6)),
    [1],
    ""
  ],
  [
    Seq.orElse(Seq.range(1, 3), Seq.range(4, 6)),
    [
      1,
      2,
      3
    ],
    ""
  ]
]);

let sortByTests = makeSeqEqualsTests("sortBy", [
  [
    Seq.sortBy(Seq.empty, Primitive_int.compare),
    [],
    ""
  ],
  [
    Seq.sortBy(Seq.once(1), Primitive_int.compare),
    [1],
    ""
  ],
  [
    Seq.sortBy(Seq.fromArray(undefined, undefined, [
      1,
      5,
      2,
      9,
      7,
      3
    ]), Primitive_int.compare),
    [
      1,
      2,
      3,
      5,
      7,
      9
    ],
    ""
  ]
]).concat([
  willNotThrow("sortBy", "lazy", () => Seq.sortBy(Seq.onceWith(throwIfInvoked), Primitive_int.compare)),
  Seq__Test.fromPredicate("Seq", "sortBy", "stable", () => {
    let sortByFirst = (a, b) => Primitive_int.compare(a[0], b[0]);
    let data = [
      [
        2,
        "x"
      ],
      [
        1,
        "x"
      ],
      [
        2,
        "y"
      ],
      [
        4,
        "x"
      ],
      [
        3,
        "x"
      ],
      [
        1,
        "y"
      ],
      [
        3,
        "y"
      ],
      [
        2,
        "z"
      ],
      [
        4,
        "y"
      ],
      [
        1,
        "z"
      ],
      [
        3,
        "z"
      ],
      [
        4,
        "z"
      ]
    ];
    let sorted = Seq.toArray(Seq.map(Seq.sortBy(Seq.fromArray(undefined, undefined, data), sortByFirst), param => param[1]));
    return Primitive_object.equal(sorted, "xyzxyzxyzxyz".split(""));
  })
]);

let delayTests = makeSeqEqualsTests("delay", [
  [
    Seq.delay(() => Seq.empty),
    [],
    ""
  ],
  [
    Seq.delay(() => Seq.once(1)),
    [1],
    ""
  ],
  [
    Seq.delay(() => Seq.range(1, 5)),
    [
      1,
      2,
      3,
      4,
      5
    ],
    ""
  ],
  [
    Seq.take(Seq.delay(() => Exn.raiseError("boom!")), 0),
    [],
    ""
  ]
]).concat([willNotThrow("delay", "lazy", () => Seq.delay(throwIfInvoked))]);

function kind(n) {
  if (n % 2 === 0) {
    return "e";
  } else {
    return "o";
  }
}

function parityCount(xx) {
  return Seq.split(xx, n => [
    kind(n),
    1
  ], (param, n) => {
    let k = param[0];
    if (kind(n) === k) {
      return [
        k,
        param[1] + 1 | 0
      ];
    }
    
  });
}

let splitTests = makeSeqEqualsTests("split", [
  [
    parityCount(Seq.fromArray(undefined, undefined, [])),
    [],
    ""
  ],
  [
    parityCount(Seq.fromArray(undefined, undefined, [1])),
    [[
        "o",
        1
      ]],
    ""
  ],
  [
    parityCount(Seq.fromArray(undefined, undefined, [
      1,
      1
    ])),
    [[
        "o",
        2
      ]],
    ""
  ],
  [
    parityCount(Seq.fromArray(undefined, undefined, [
      1,
      1,
      1
    ])),
    [[
        "o",
        3
      ]],
    ""
  ],
  [
    parityCount(Seq.fromArray(undefined, undefined, [
      1,
      1,
      1,
      2
    ])),
    [
      [
        "o",
        3
      ],
      [
        "e",
        1
      ]
    ],
    ""
  ],
  [
    parityCount(Seq.fromArray(undefined, undefined, [
      1,
      2,
      2,
      2,
      3,
      2,
      2,
      1
    ])),
    [
      [
        "o",
        1
      ],
      [
        "e",
        3
      ],
      [
        "o",
        1
      ],
      [
        "e",
        2
      ],
      [
        "o",
        1
      ]
    ],
    ""
  ]
]).concat([
  seqEqual("split", "millions in an output group", () => parityCount(Seq.concat(Seq.replicate(1, 500000), Seq.replicate(0, 500000))), [
    [
      "o",
      500000
    ],
    [
      "e",
      500000
    ]
  ]),
  seqEqual("split", "millions of source items", () => Seq.drop(parityCount(Seq.take(Seq.cycle(Seq.fromArray(undefined, undefined, [
    1,
    2
  ])), 1000000)), 999998), [
    [
      "o",
      1
    ],
    [
      "e",
      1
    ]
  ]),
  willNotThrow("split", "lazy", () => parityCount(Seq.onceWith(throwIfInvoked)))
]);

function sortLetters(w) {
  return w.split("").toSorted((prim0, prim1) => prim0.localeCompare(prim1)).join("");
}

function sortOutput(combos) {
  return Seq.toArray(Seq.sortBy(Seq.map(combos, combo => sortLetters(Seq.reduce(combo, "", (sum, i) => sum + i))), (prim0, prim1) => prim0.localeCompare(prim1))).join(",");
}

function sort(words) {
  return words.split(",").map(sortLetters).toSorted((prim0, prim1) => prim0.localeCompare(prim1)).join(",");
}

function combos$1(letters, k) {
  return Seq.combinations(Seq.fromArray(undefined, undefined, letters.split("")), k);
}

function comboString(letters, k) {
  return sortOutput(Seq.map(combos$1(letters, k), param => param[1]));
}

function permutes(letters, k) {
  return Seq.permutations(Seq.fromArray(undefined, undefined, letters.split("")), k);
}

function permuteString(letters, k) {
  return sortOutput(Seq.map(permutes(letters, k), param => param[1]));
}

let comboSamples = makeValueEqualTests("combinations", [
  [
    () => comboString("", 1),
    sort(""),
    ""
  ],
  [
    () => comboString("a", 1),
    sort("a"),
    ""
  ],
  [
    () => comboString("a", 2),
    sort("a"),
    ""
  ],
  [
    () => comboString("ab", 1),
    sort("a,b"),
    ""
  ],
  [
    () => comboString("ab", 2),
    sort("a,b,ab"),
    ""
  ],
  [
    () => comboString("ab", 3),
    sort("a,b,ab"),
    ""
  ],
  [
    () => comboString("abc", 1),
    sort("a,b,c"),
    ""
  ],
  [
    () => comboString("abc", 2),
    sort("a,b,c,ab,ac,bc"),
    ""
  ],
  [
    () => comboString("abc", 3),
    sort("a,b,c,ab,ac,bc,abc"),
    ""
  ],
  [
    () => comboString("abc", 4),
    sort("a,b,c,ab,ac,bc,abc"),
    ""
  ],
  [
    () => sortOutput(Seq.filterMap(combos$1("abc", 4), param => {
      if (param[0] === 1) {
        return Primitive_option.some(param[1]);
      }
      
    })),
    sort("a,c,b"),
    "check size == 1 in result"
  ],
  [
    () => sortOutput(Seq.filterMap(combos$1("abc", 4), param => {
      if (param[0] === 3) {
        return Primitive_option.some(param[1]);
      }
      
    })),
    sort("abc"),
    "check size == 3 in result"
  ],
  [
    () => sortOutput(Seq.map(Seq.combinations(Seq.take(Seq.map(Seq.foreverWith(callCount()), i => {
      if (i === 1) {
        return "a";
      } else if (i === 2) {
        return "b";
      } else if (i === 3) {
        return "c";
      } else {
        return "x";
      }
    }), 3), 3), param => param[1])),
    sort("a,b,c,ab,ac,bc,abc"),
    "values appear cached"
  ]
]);

let permuteSamples = makeValueEqualTests("permutations", [
  [
    () => permuteString("", 1),
    sort(""),
    ""
  ],
  [
    () => permuteString("a", 1),
    sort("a"),
    ""
  ],
  [
    () => permuteString("a", 2),
    sort("a"),
    ""
  ],
  [
    () => permuteString("ab", 1),
    sort("a,b"),
    ""
  ],
  [
    () => permuteString("ab", 2),
    sort("a,b,ab,ba"),
    ""
  ],
  [
    () => permuteString("ab", 3),
    sort("a,b,ab,ba"),
    ""
  ],
  [
    () => permuteString("abc", 1),
    sort("a,b,c"),
    ""
  ],
  [
    () => permuteString("abc", 2),
    sort("a,b,c,ab,ac,bc,ba,ca,cb"),
    ""
  ],
  [
    () => permuteString("abc", 3),
    sort("a,b,c,ab,ac,bc,ba,ca,cb,abc,acb,bac,bca,cab,cba"),
    ""
  ],
  [
    () => permuteString("abc", 4),
    sort("a,b,c,ab,ac,bc,ba,ca,cb,abc,acb,bac,bca,cab,cba"),
    ""
  ],
  [
    () => sortOutput(Seq.filterMap(permutes("abc", 4), param => {
      if (param[0] === 1) {
        return Primitive_option.some(param[1]);
      }
      
    })),
    sort("a,c,b"),
    "check size == 1 in result"
  ],
  [
    () => sortOutput(Seq.filterMap(permutes("abc", 4), param => {
      if (param[0] === 3) {
        return Primitive_option.some(param[1]);
      }
      
    })),
    sort("abc,acb,bac,bca,cab,cba"),
    "check size == 3 in result"
  ],
  [
    () => sortOutput(Seq.map(Seq.permutations(Seq.take(Seq.map(Seq.foreverWith(callCount()), i => {
      if (i === 1) {
        return "a";
      } else if (i === 2) {
        return "b";
      } else if (i === 3) {
        return "c";
      } else {
        return "x";
      }
    }), 3), 3), param => param[1])),
    sort("a,b,c,ab,ac,bc,ba,ca,cb,abc,acb,bac,bca,cab,cba"),
    "values appear cached"
  ]
]);

function miscellaneous(title, f) {
  return [
    willThrow(title, "if size < 0 throw", () => f(Seq.range(1, 9), -1)),
    willThrow(title, "if size = 0 throw", () => f(Seq.range(1, 9), 0)),
    valueEqual(title, "millions - take 10", () => Option.isSome(Seq.last(Seq.take(f(Seq.range(1, 1000), 1000), 10))), true),
    valueEqual(title, "infinite - take 0", () => Seq.last(Seq.take(f(Seq.foreverWith(() => 1), 1000), 0)), undefined),
    valueEqual(title, "infinite - take 1", () => Option.isSome(Seq.last(Seq.take(f(Seq.foreverWith(() => 1), 1000), 4))), true),
    valueEqual(title, "totally lazy", () => Seq.last(Seq.take(f(Seq.replicateWith(throwIfInvoked, 3), 1000), 0)), undefined)
  ];
}

let combinationTests = [
  comboSamples,
  miscellaneous("combinations", Seq.combinations)
].flatMap(i => i);

let permutationTests = [
  permuteSamples,
  miscellaneous("permutations", Seq.permutations)
].flatMap(i => i);

let toListTests = makeValueEqualTests("toList", [
  [
    () => Seq.toList(Seq.empty),
    /* [] */0,
    ""
  ],
  [
    () => Seq.toList(Seq.once(1)),
    {
      hd: 1,
      tl: /* [] */0
    },
    ""
  ],
  [
    () => Seq.toList(Seq.fromArray(undefined, undefined, [
      1,
      2
    ])),
    {
      hd: 1,
      tl: {
        hd: 2,
        tl: /* [] */0
      }
    },
    ""
  ],
  [
    () => Seq.toList(Seq.fromArray(undefined, undefined, [
      1,
      2,
      3
    ])),
    {
      hd: 1,
      tl: {
        hd: 2,
        tl: {
          hd: 3,
          tl: /* [] */0
        }
      }
    },
    ""
  ],
  [
    () => Option.getExn(List.drop(Seq.toList(Seq.range(1, 9999)), 9998), undefined),
    {
      hd: 9999,
      tl: /* [] */0
    },
    ""
  ]
]);

let tailsTests = makeSeqEqualsTests("tails", [
  [
    Seq.map(Seq.tails(Seq.empty), Seq.toArray),
    [[]],
    ""
  ],
  [
    Seq.map(Seq.tails(Seq.once(1)), Seq.toArray),
    [
      [1],
      []
    ],
    ""
  ],
  [
    Seq.map(Seq.tails(Seq.range(1, 3)), Seq.toArray),
    [
      [
        1,
        2,
        3
      ],
      [
        2,
        3
      ],
      [3],
      []
    ],
    ""
  ]
]);

function test$2(source, count, result) {
  return valueEqual("dropLast", "[" + source + "] " + count.toString() + " => [" + result + "]", () => Seq.join(Seq.dropLast(Seq.fromArray(undefined, undefined, source.split("")), count), ""), result);
}

let dropLastTests = [
  test$2("", 1, ""),
  test$2("", 99, ""),
  test$2("a", 1, ""),
  test$2("a", 99, ""),
  test$2("ab", 1, "a"),
  test$2("ab", 2, ""),
  test$2("ab", 99, ""),
  test$2("abc", 1, "ab"),
  test$2("abc", 2, "a"),
  test$2("abc", 3, ""),
  test$2("abc", 99, ""),
  test$2("abcdefg", 1, "abcdef")
].concat([
  willNotThrow("dropLast", "lazy", () => Seq.dropLast(Seq.onceWith(throwIfInvoked), 10)),
  willThrow("dropLast", "when count < 0, throw", () => Seq.dropLast(Seq.range(1, 5), -1)),
  valueEqual("dropLast", "when count = 0 return same instance", () => {
    let source = Seq.range(1, 5);
    let result = Seq.dropLast(source, 0);
    return source === result;
  }, true)
]);

let sampleFibonacci = makeSeqEqualsTests("sampleFibonacci", [[
    Seq.fromArray(undefined, undefined, Seq__SeqSamples.fibonacci(12)),
    [
      0,
      1,
      1,
      2,
      3,
      5,
      8,
      13,
      21,
      34,
      55,
      89
    ],
    ""
  ]]);

function compute(xx, yy) {
  return Seq__SeqSamples.zipLongest(Seq.fromArray(undefined, undefined, xx), Seq.fromArray(undefined, undefined, yy));
}

let sampleZipLongest = makeSeqEqualsTests("sampleZipLongest", [
  [
    compute([
      1,
      2
    ], [
      "x",
      "y",
      "z"
    ]),
    [
      [
        1,
        "x"
      ],
      [
        2,
        "y"
      ],
      [
        undefined,
        "z"
      ]
    ],
    ""
  ],
  [
    compute([], [
      "x",
      "y",
      "z"
    ]),
    [
      [
        undefined,
        "x"
      ],
      [
        undefined,
        "y"
      ],
      [
        undefined,
        "z"
      ]
    ],
    ""
  ]
]);

let sampleBinaryDigits = makeSeqEqualsTests("sampleBinaryDigits", [
  [
    Seq.fromArray(undefined, undefined, Seq__SeqSamples.binary(15)),
    [
      1,
      1,
      1,
      1
    ],
    ""
  ],
  [
    Seq.fromArray(undefined, undefined, Seq__SeqSamples.binary(8)),
    [
      1,
      0,
      0,
      0
    ],
    ""
  ],
  [
    Seq.fromArray(undefined, undefined, Seq__SeqSamples.binary(435195)),
    [
      1,
      1,
      0,
      1,
      0,
      1,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1
    ],
    ""
  ]
]);

let sampleLocalMinimums = [
  valueEqual("sampleLocalMinimums", "", () => Seq__SeqSamples.localMinimums([
    [
      4,
      4
    ],
    [
      7,
      0
    ],
    [
      10,
      12
    ]
  ]), "(7, 0)"),
  valueEqual("sampleLocalMinimums", "", () => Seq__SeqSamples.localMinimums([
    [
      4,
      4
    ],
    [
      7,
      0
    ],
    [
      10,
      12
    ],
    [
      15,
      -1
    ],
    [
      99,
      3
    ]
  ]), "(7, 0), (15, -1)"),
  valueEqual("sampleLocalMinimums", "", () => Seq__SeqSamples.localMinimums([
    [
      4,
      4
    ],
    [
      7,
      19
    ],
    [
      10,
      99
    ]
  ]), "There are no local minimums.")
];

let sampleRunningTotal = makeSeqEqualsTests("sampleRunningTotal", [
  [
    Seq__SeqSamples.runningTotal([
      1,
      2,
      3,
      4
    ]),
    [
      0,
      1,
      3,
      6,
      10
    ],
    ""
  ],
  [
    Seq__SeqSamples.runningTotal([]),
    [0],
    ""
  ],
  [
    Seq__SeqSamples.runningTotal([
      3,
      3,
      3,
      3
    ]),
    [
      0,
      3,
      6,
      9,
      12
    ],
    ""
  ]
]);

let sampleMultiplicationTableTests = makeValueEqualTests("sampleMultiplicationTable", [
  [
    () => Seq__SeqSamples.multiplicationTable[1][4],
    4,
    ""
  ],
  [
    () => Seq__SeqSamples.multiplicationTable[8][9],
    72,
    ""
  ],
  [
    () => Seq__SeqSamples.multiplicationTable[8][9],
    72,
    ""
  ],
  [
    () => Seq__SeqSamples.multiplicationTable[2][5],
    10,
    ""
  ],
  [
    () => Seq__SeqSamples.multiplicationTable[9][2],
    18,
    ""
  ]
]);

let sampleRemoveDups = makeSeqEqualsTests("sampleRemoveDups", [
  [
    Seq__SeqSamples.removeDups([
      1,
      2,
      2,
      3,
      3,
      3
    ]),
    [
      1,
      2,
      3
    ],
    ""
  ],
  [
    Seq__SeqSamples.removeDups([1]),
    [1],
    ""
  ],
  [
    Seq__SeqSamples.removeDups([]),
    [],
    ""
  ],
  [
    Seq__SeqSamples.removeDups([
      1,
      1,
      2,
      2,
      2,
      3,
      3,
      3,
      3
    ]),
    [
      1,
      2,
      3
    ],
    ""
  ]
]);

let tests = [
  atTests,
  allPairsTests,
  chunkBySizeTests,
  combinationTests,
  compareTests,
  concatTests,
  consTests,
  consumeTests,
  cycleTests,
  delayTests,
  dropLastTests,
  dropTests,
  dropUntilTests,
  dropWhileTests,
  emptyTests,
  equalsTests,
  everyOkTests,
  everySomeTests,
  everyTests,
  exactlyOneTests,
  unfoldManyTests,
  filterMapiTests,
  filterMapTests,
  filterOkTests,
  filterSomeTests,
  filterTests,
  findLastTests,
  findMapLastTests,
  findMapTests,
  findTests,
  flatMapTests,
  flattenTests,
  forEachTests,
  foreverTests,
  foreverWithTests,
  fromArrayTests,
  fromListTests,
  headTests,
  indexedTests,
  initTests,
  interleaveTests,
  intersperseTests,
  intersperseWithTests,
  isEmptyTests,
  isSortedByTests,
  iterateTests,
  iterateWhileTests,
  joinTests,
  lastTests,
  lengthTests,
  map2Tests,
  map3Tests,
  mapTests,
  memoizeTests,
  minByMaxByTests,
  neighborsTests,
  onceTests,
  onceWithTests,
  orElseTests,
  pairAheadTests,
  pairBehindTests,
  pairwiseTests,
  permutationTests,
  prefixSumTests,
  prependTests,
  rangeMapTests,
  rangeTests,
  reduceTests,
  reduceUntilTests,
  reduceWhileTests,
  replicateTests,
  replicateWithTests,
  reverseTests,
  sampleBinaryDigits,
  sampleFibonacci,
  sampleLocalMinimums,
  sampleMultiplicationTableTests,
  sampleRemoveDups,
  sampleRunningTotal,
  sampleZipLongest,
  scanTests,
  someTests,
  sortByTests,
  sortedMergeTests,
  splitTests,
  sumTests,
  tailsTests,
  tailTests,
  takeTests,
  takeUntilTests,
  takeWhileTests,
  tapTests,
  toArrayTests,
  toListTests,
  toOptionTests,
  unconsTests,
  unfoldTests,
  windowTests
].flatMap(i => i);

let T;

let S;

let R;

export {
  T,
  S,
  R,
  characters,
  joinInts,
  shorten,
  trueAlways,
  falseAlways,
  callCount,
  callCountForever,
  throwIfInvoked,
  death,
  toDispenser,
  countdown,
  seqEqual,
  valueEqual,
  willThrow,
  willNotThrow,
  makeSeqEqualsTests,
  makeValueEqualTests,
  onceTests,
  onceWithTests,
  emptyTests,
  consTests,
  fromListTests,
  cycleTests,
  allPairsTests,
  rangeTests,
  rangeMapTests,
  concatTests,
  prependTests,
  flatMapTests,
  mapTests,
  indexedTests,
  takeWhileTests,
  dropTests,
  flattenTests,
  sortedMergeTests,
  tapTests,
  windowTests,
  pairAheadTests,
  pairBehindTests,
  neighborsTests,
  pairwiseTests,
  interleaveTests,
  iterateTests,
  iterateWhileTests,
  fromArrayTests,
  replicateTests,
  replicateWithTests,
  foreverTests,
  takeTests,
  foreverWithTests,
  unfoldTests,
  unfoldManyTests,
  initTests,
  chunkBySizeTests,
  scanTests,
  takeUntilTests,
  intersperseTests,
  intersperseWithTests,
  dropWhileTests,
  filterSomeTests,
  filterOkTests,
  filterMapTests,
  filterMapiTests,
  filterTests,
  dropUntilTests,
  forEachTests,
  someTests,
  everyTests,
  findMapLastTests,
  findMapTests,
  toArrayTests,
  lengthTests,
  equalsTests,
  compareTests,
  unconsTests,
  tailTests,
  headTests,
  minByMaxByTests,
  isEmptyTests,
  joinTests,
  exactlyOneTests,
  isSortedByTests,
  toOptionTests,
  reduceTests,
  reduceUntilTests,
  reduceWhileTests,
  sumTests,
  prefixSumTests,
  lastTests,
  atTests,
  everyOkTests,
  everySomeTests,
  memoizeTests,
  findTests,
  findLastTests,
  map2Tests,
  map3Tests,
  consumeTests,
  reverseTests,
  orElseTests,
  sortByTests,
  delayTests,
  splitTests,
  combinationTests,
  permutationTests,
  toListTests,
  tailsTests,
  dropLastTests,
  sampleFibonacci,
  sampleZipLongest,
  sampleBinaryDigits,
  sampleLocalMinimums,
  sampleRunningTotal,
  sampleMultiplicationTableTests,
  sampleRemoveDups,
  tests,
}
/* onceTests Not a pure module */
