// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Seq__Task from "../src/Seq__Task.mjs";
import * as Seq__Test from "../src/Seq__Test.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_exceptions from "rescript/lib/es6/Primitive_exceptions.js";

let OutOfRange = /* @__PURE__ */Primitive_exceptions.create("Seq__TaskTest.OutOfRange");

function failsOutOfRange(success, outOfRange) {
  return Promise.resolve(success).then(param => {
    throw {
      RE_EXN_ID: OutOfRange,
      _1: outOfRange,
      Error: new Error()
    };
  });
}

function failsJsException(success, msg) {
  return Promise.resolve(success).then(param => Exn.raiseError(msg));
}

function makeTest(title, expectation, a, b) {
  return Seq__Test.fromPredicateAsync("Task", title, expectation, async () => Primitive_object.equal(await Seq__Task.toPromise(a()), b));
}

let taskTests = [
  makeTest("make", "when succeeds, return value", () => Seq__Task.make(() => Promise.resolve(99), param => -1), 99),
  makeTest("make", "when fails with ReScript exception, return value after onError processes exn", () => Seq__Task.make(() => failsOutOfRange("ok", 4), e => {
    if (e.RE_EXN_ID === OutOfRange) {
      return (e._1 << 1);
    } else {
      return -1;
    }
  }), 8),
  makeTest("make", "when fails with JavaScript exception, return value after onError processes exn", () => Seq__Task.make(() => failsJsException(99, "failure"), e => {
    if (e.RE_EXN_ID === Exn.$$Error) {
      return Option.getOr(e._1.message, "no message in exception");
    } else {
      return "exception was not caught";
    }
  }), "failure"),
  makeTest("map", "return value mapped", () => Seq__Task.map(Seq__Task.map(Seq__Task.map(Seq__Task.make(() => Promise.resolve(2), param => -99), i => (i << 1)), i => Math.imul(i, 3)), i => "It is " + i.toString()), "It is 12"),
  Seq__Test.fromPredicateAsync("Task", "spy", "spy function is executed", async () => {
    let saw = {
      contents: -1
    };
    let t = Seq__Task.map(Seq__Task.spy(Seq__Task.make(() => Promise.resolve(99), param => -1), v => {
      saw.contents = v;
    }), i => (i << 1));
    await Seq__Task.toPromise(t);
    return saw.contents === 99;
  })
];

function succeedsTask(success, onError) {
  return Seq__Task.Result.make(() => Promise.resolve(success), param => onError);
}

function makeTest$1(title, expectation, a, b) {
  return Seq__Test.fromPredicateAsync("Task.Result", title, expectation, async () => Primitive_object.equal(await Seq__Task.toPromise(a()), b));
}

let taskResultTests = [
  makeTest$1("make", "when succeeds, return Ok", () => succeedsTask(11, "error"), {
    TAG: "Ok",
    _0: 11
  }),
  makeTest$1("make", "when fails with ReScript exception, return Error with onError processing exn", () => Seq__Task.Result.make(() => failsOutOfRange("abc", 4), e => {
    if (e.RE_EXN_ID === OutOfRange) {
      return (e._1 << 1);
    } else {
      return -1;
    }
  }), {
    TAG: "Error",
    _0: 8
  }),
  makeTest$1("make", "when fails with ReScript exception, can map error later", () => Seq__Task.Result.mapError(Seq__Task.Result.make(() => failsOutOfRange("abc", 4), e => e), e => {
    if (e.RE_EXN_ID === OutOfRange) {
      return (e._1 << 1);
    } else {
      return -1;
    }
  }), {
    TAG: "Error",
    _0: 8
  }),
  makeTest$1("make", "when fails with JavaScript exception, return Error with onError processing exn", () => Seq__Task.Result.make(() => failsJsException("success", "failure"), e => {
    if (e.RE_EXN_ID === Exn.$$Error) {
      return Option.getOr(e._1.message, "no message in exception");
    } else {
      return "exception was not caught";
    }
  }), {
    TAG: "Error",
    _0: "failure"
  }),
  makeTest$1("make", "when fails with JavaScript exception, can map error later", () => Seq__Task.Result.mapError(Seq__Task.Result.make(() => failsJsException("abc", "failure"), e => e), e => {
    if (e.RE_EXN_ID === Exn.$$Error) {
      return Option.mapOr(e._1.message, false, i => i === "failure");
    } else {
      return false;
    }
  }), {
    TAG: "Error",
    _0: true
  }),
  makeTest$1("mapOk", "when succeeds, return Ok mapped", () => Seq__Task.Result.mapOk(Seq__Task.Result.mapOk(succeedsTask(11, "abc"), i => (i << 1)), i => Math.imul(i, 5)), {
    TAG: "Ok",
    _0: 110
  }),
  makeTest$1("mapError", "when fails, return Error mapped", () => Seq__Task.Result.mapError(Seq__Task.Result.mapError(Seq__Task.Result.make(() => failsOutOfRange("abc", 4), param => 3), i => (i << 1)), i => i + 9 | 0), {
    TAG: "Error",
    _0: 15
  }),
  makeTest$1("flatMap", "when succeeds, return Ok", () => Seq__Task.Result.flatMap(Seq__Task.Result.flatMap(succeedsTask(11, -1), i => {
    if (i === 11) {
      return {
        TAG: "Ok",
        _0: 88
      };
    } else {
      return {
        TAG: "Error",
        _0: -1
      };
    }
  }), i => {
    if (i === 88) {
      return {
        TAG: "Ok",
        _0: 65
      };
    } else {
      return {
        TAG: "Error",
        _0: -1
      };
    }
  }), {
    TAG: "Ok",
    _0: 65
  }),
  makeTest$1("flatMap", "when fails eventually, return first Error", () => Seq__Task.Result.flatMap(Seq__Task.Result.flatMap(Seq__Task.Result.flatMap(succeedsTask(11, 3), i => {
    if (i === 11) {
      return {
        TAG: "Ok",
        _0: 88
      };
    } else {
      return {
        TAG: "Error",
        _0: -1
      };
    }
  }), i => {
    if (i === 88) {
      return {
        TAG: "Error",
        _0: 1234
      };
    } else {
      return {
        TAG: "Ok",
        _0: -1
      };
    }
  }), param => ({
    TAG: "Error",
    _0: 55
  })), {
    TAG: "Error",
    _0: 1234
  }),
  makeTest$1("flatMap", "when fails immediately, return first Error", () => Seq__Task.Result.flatMap(Seq__Task.Result.flatMap(Seq__Task.Result.make(() => failsOutOfRange(11, 4), param => 103), param => ({
    TAG: "Error",
    _0: -1
  })), param => ({
    TAG: "Error",
    _0: 31
  })), {
    TAG: "Error",
    _0: 103
  }),
  makeTest$1("toOption", "when succeeds, return Some", () => Seq__Task.Result.toOption(succeedsTask(99, 3)), 99),
  makeTest$1("toOption", "when fails, return None", () => Seq__Task.Result.toOption(Seq__Task.Result.make(() => failsOutOfRange(11, 4), param => 3)), undefined)
];

let tests = taskTests.concat(taskResultTests);

let T;

let Task;

let ResultEx;

export {
  T,
  Task,
  ResultEx,
  OutOfRange,
  failsOutOfRange,
  failsJsException,
  taskTests,
  taskResultTests,
  tests,
}
/* taskTests Not a pure module */
