// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Seq__Task from "../src/Seq__Task.mjs";
import * as Seq__Test from "../src/Seq__Test.mjs";
import * as Seq__SeqTests from "./Seq__SeqTests.mjs";
import * as Seq__TaskTest from "./Seq__TaskTest.mjs";
import * as Seq__OptionTests from "./Seq__OptionTests.mjs";
import * as Seq__ResultTests from "./Seq__ResultTests.mjs";

function isLocalDevelopment() {
  try {
    return (process.env.NODE_ENV === "development");
  } catch (exn) {
    return false;
  }
}

function filter(test) {
  return [].every(word => Seq__Test.hasKeyword(test, word));
}

let throwOnFailure = !isLocalDevelopment();

let tests = [
  Seq__OptionTests.tests,
  Seq__ResultTests.allTests,
  Seq__TaskTest.tests,
  Seq__SeqTests.tests
].flat();

Seq__Task.toPromise(Seq__Task.forEach(Seq__Task.Result.make(() => Seq__Test.runSuite(filter, false, tests), e => e), s => {
  if (s.TAG !== "Ok") {
    if (throwOnFailure) {
      return Exn.raiseError("Could not complete the test suite.");
    } else {
      return;
    }
  }
  if (!throwOnFailure) {
    return;
  }
  let s$1 = s._0;
  if (s$1.fail > 0) {
    return Exn.raiseError("Tests failed: " + s$1.fail.toString());
  }
  
}));

let Test;

let Task;

let Q;

let onlyShowFailures = false;

export {
  Test,
  Task,
  Q,
  isLocalDevelopment,
  onlyShowFailures,
  filter,
  throwOnFailure,
  tests,
}
/* throwOnFailure Not a pure module */
