// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lazy from "rescript/lib/es6/Lazy.js";
import * as List from "rescript/lib/es6/List.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Result from "rescript/lib/es6/Result.js";
import * as Seq__Option from "./Seq__Option.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "rescript/lib/es6/Primitive_exceptions.js";

let InvalidArgument = /* @__PURE__ */Primitive_exceptions.create("Seq.InvalidArgument");

function delay(generator) {
  return () => generator()();
}

function empty() {
  return "End";
}

function once(x) {
  return () => ({
    TAG: "Next",
    _0: x,
    _1: empty
  });
}

function onceWith(f) {
  return () => ({
    TAG: "Next",
    _0: f(),
    _1: empty
  });
}

function cons(x, xx) {
  return () => ({
    TAG: "Next",
    _0: x,
    _1: xx
  });
}

function uncons(xx) {
  let match = xx();
  if (typeof match !== "object") {
    return;
  } else {
    return [
      match._0,
      match._1
    ];
  }
}

function find(xx, f) {
  let _xx = xx;
  while (true) {
    let xx$1 = _xx;
    let match = xx$1();
    if (typeof match !== "object") {
      return;
    }
    let x = match._0;
    if (f(x)) {
      return Primitive_option.some(x);
    }
    _xx = match._1;
    continue;
  };
}

function findLast(xx, f) {
  let _xx = xx;
  let _last;
  while (true) {
    let last = _last;
    let xx$1 = _xx;
    let match = xx$1();
    if (typeof match !== "object") {
      return last;
    }
    let xx$2 = match._1;
    let x = match._0;
    if (f(x)) {
      _last = Primitive_option.some(x);
      _xx = xx$2;
      continue;
    }
    _xx = xx$2;
    continue;
  };
}

function concat(xx, yy) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return yy();
    } else {
      return {
        TAG: "Next",
        _0: match._0,
        _1: concat(match._1, yy)
      };
    }
  };
}

function prepend(xx, yy) {
  return concat(yy, xx);
}

function flatMap(xx, f) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return concat(f(match._0), flatMap(match._1, f))();
    }
  };
}

function flatten(xxx) {
  return () => {
    let match = xxx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return concat(match._0, flatten(match._1))();
    }
  };
}

function map(xx, f) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return {
        TAG: "Next",
        _0: f(match._0),
        _1: map(match._1, f)
      };
    }
  };
}

function head(xx) {
  let match = xx();
  if (typeof match !== "object") {
    return;
  } else {
    return Primitive_option.some(match._0);
  }
}

function indexed(xx) {
  let go = (xx, index) => (() => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return {
        TAG: "Next",
        _0: [
          match._0,
          index
        ],
        _1: go(match._1, index + 1 | 0)
      };
    }
  });
  return go(xx, 0);
}

function forEach(_xx, f) {
  while (true) {
    let xx = _xx;
    let match = uncons(xx);
    if (match === undefined) {
      return;
    }
    f(match[0]);
    _xx = match[1];
    continue;
  };
}

function forEachi(xx, f) {
  forEach(indexed(xx), param => f(param[0], param[1]));
}

function unfold(seed, f) {
  return () => {
    let match = f(seed);
    if (match !== undefined) {
      return {
        TAG: "Next",
        _0: match[0],
        _1: unfold(match[1], f)
      };
    } else {
      return "End";
    }
  };
}

function init(count, f) {
  return unfold(0, i => {
    if (i < count) {
      return [
        f(i),
        i + 1 | 0
      ];
    }
    
  });
}

function replicate(value, count) {
  return unfold(0, i => {
    if (i < count) {
      return [
        value,
        i + 1 | 0
      ];
    }
    
  });
}

function replicateWith(value, count) {
  return unfold(1, i => {
    if (i <= count) {
      return [
        value(),
        i + 1 | 0
      ];
    }
    
  });
}

function forever(value) {
  return () => ({
    TAG: "Next",
    _0: value,
    _1: forever(value)
  });
}

function foreverWith(f) {
  return () => ({
    TAG: "Next",
    _0: f(),
    _1: foreverWith(f)
  });
}

function iterate(seed, f) {
  return unfold(seed, i => [
    i,
    f(i)
  ]);
}

function range(start, end) {
  if (start <= end) {
    return unfold(start, i => {
      if (i <= end) {
        return [
          i,
          i + 1 | 0
        ];
      }
      
    });
  } else {
    return unfold(start, i => {
      if (i >= end) {
        return [
          i,
          i - 1 | 0
        ];
      }
      
    });
  }
}

function rangeMap(start, end, f) {
  return map(range(start, end), f);
}

function tap(xx, f) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let x = match._0;
    f(x);
    return {
      TAG: "Next",
      _0: x,
      _1: tap(match._1, f)
    };
  };
}

function cycleNonEmpty(xx) {
  return () => concat(xx, cycleNonEmpty(xx))();
}

function cycle(xx) {
  return () => {
    let match = uncons(xx);
    if (match === undefined) {
      return "End";
    }
    let xx$p = match[1];
    let x = match[0];
    return concat(() => ({
      TAG: "Next",
      _0: x,
      _1: xx$p
    }), cycleNonEmpty(xx))();
  };
}

function fromArray(start, end, xx) {
  if (xx.length === 0) {
    Option.forEach(Option.orElse(start, end), param => {
      throw {
        RE_EXN_ID: InvalidArgument,
        _1: "'fromArray' was invoked with am empty array, but you provided start and/or end indexes.",
        Error: new Error()
      };
    });
    return empty;
  }
  let len = xx.length;
  let start$1 = Option.getOr(start, 0);
  let end$1 = Option.getOr(end, len - 1 | 0);
  if (start$1 < 0 || start$1 > (len - 1 | 0)) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "The start index " + start$1.toString() + " is outside the array bounds.",
      Error: new Error()
    };
  }
  if (end$1 < 0 || end$1 > (len - 1 | 0)) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "The end index " + start$1.toString() + " is outside the array bounds.",
      Error: new Error()
    };
  }
  return map(range(start$1, end$1), inx => xx[inx]);
}

function fromList(xx) {
  return () => {
    if (xx) {
      return {
        TAG: "Next",
        _0: xx.hd,
        _1: fromList(xx.tl)
      };
    } else {
      return "End";
    }
  };
}

function mapi(xx, f) {
  return map(indexed(xx), param => f(param[0], param[1]));
}

function take(xx, count) {
  if (count < 0) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "'take' requires a count of 0 or more. You requested " + count.toString(),
      Error: new Error()
    };
  }
  let go = (xx, count) => (() => {
    if (count === 0) {
      return "End";
    }
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return {
        TAG: "Next",
        _0: match._0,
        _1: go(match._1, count - 1 | 0)
      };
    }
  });
  return go(xx, count);
}

function headTails(xx) {
  return unfold(xx, xx => Option.flatMap(uncons(xx), ht => [
    ht,
    ht[1]
  ]));
}

function drop(xx, count) {
  if (count === 0) {
    return xx;
  }
  if (count < 0) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "'drop' requires a count of zero or more but you asked for " + count.toString(),
      Error: new Error()
    };
  }
  let generator = () => {
    let _xx = xx;
    let _count = count;
    while (true) {
      let count$1 = _count;
      let xx$1 = _xx;
      if (count$1 === 0) {
        return xx$1;
      }
      let match = uncons(xx$1);
      if (match === undefined) {
        return empty;
      }
      _count = count$1 - 1 | 0;
      _xx = match[1];
      continue;
    };
  };
  return () => generator()();
}

function filter(xx, f) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let xx$1 = match._1;
    let x = match._0;
    if (f(x)) {
      return {
        TAG: "Next",
        _0: x,
        _1: filter(xx$1, f)
      };
    }
    let match$1 = find(headTails(xx$1), param => f(param[0]));
    if (match$1 !== undefined) {
      return {
        TAG: "Next",
        _0: match$1[0],
        _1: filter(match$1[1], f)
      };
    } else {
      return "End";
    }
  };
}

function filteri(xx, f) {
  return map(filter(indexed(xx), param => f(param[0], param[1])), param => param[0]);
}

function takeWhile(xx, f) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let x = match._0;
    if (f(x)) {
      return {
        TAG: "Next",
        _0: x,
        _1: takeWhile(match._1, f)
      };
    } else {
      return "End";
    }
  };
}

function takeUntil(xx, f) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let x = match._0;
    if (f(x)) {
      return {
        TAG: "Next",
        _0: x,
        _1: empty
      };
    } else {
      return {
        TAG: "Next",
        _0: x,
        _1: takeUntil(match._1, f)
      };
    }
  };
}

function filterMapi(xx, f) {
  let go = _xx => {
    while (true) {
      let xx = _xx;
      let match = uncons(xx);
      if (match === undefined) {
        return;
      }
      let xx$1 = match[1];
      let match$1 = match[0];
      let x = f(match$1[0], match$1[1]);
      if (x !== undefined) {
        return [
          Primitive_option.valFromOption(x),
          xx$1
        ];
      }
      _xx = xx$1;
      continue;
    };
  };
  return unfold(indexed(xx), go);
}

function filterMap(xx, f) {
  let go = _xx => {
    while (true) {
      let xx = _xx;
      let match = uncons(xx);
      if (match === undefined) {
        return;
      }
      let xx$1 = match[1];
      let x = f(match[0]);
      if (x !== undefined) {
        return [
          Primitive_option.valFromOption(x),
          xx$1
        ];
      }
      _xx = xx$1;
      continue;
    };
  };
  return unfold(xx, go);
}

function filterSome(xx) {
  let go = _xx => {
    while (true) {
      let xx = _xx;
      let match = uncons(xx);
      if (match === undefined) {
        return;
      }
      let xx$1 = match[1];
      let x = match[0];
      if (x !== undefined) {
        return [
          Primitive_option.valFromOption(x),
          xx$1
        ];
      }
      _xx = xx$1;
      continue;
    };
  };
  return unfold(xx, go);
}

function filterOk(xx) {
  return filterMap(xx, x => {
    if (x.TAG === "Ok") {
      return Primitive_option.some(x._0);
    }
    
  });
}

function scan(xx, zero, f) {
  let go = (xx, sum) => (() => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let sum$1 = f(sum, match._0);
    return {
      TAG: "Next",
      _0: sum$1,
      _1: go(match._1, sum$1)
    };
  });
  return concat(() => ({
    TAG: "Next",
    _0: zero,
    _1: empty
  }), go(xx, zero));
}

function sortedMerge(xx, yy, cmp) {
  return () => {
    let match = xx();
    let match$1 = yy();
    if (typeof match !== "object") {
      if (typeof match$1 !== "object") {
        return "End";
      } else {
        return match$1;
      }
    }
    let xx$1 = match._1;
    let x = match._0;
    if (typeof match$1 !== "object") {
      return match;
    }
    let yy$1 = match$1._1;
    let y = match$1._0;
    let order = cmp(x, y);
    if (order <= 0.0) {
      return {
        TAG: "Next",
        _0: x,
        _1: sortedMerge(xx$1, concat(() => ({
          TAG: "Next",
          _0: y,
          _1: empty
        }), yy$1), cmp)
      };
    } else {
      return {
        TAG: "Next",
        _0: y,
        _1: sortedMerge(concat(() => ({
          TAG: "Next",
          _0: x,
          _1: empty
        }), xx$1), yy$1, cmp)
      };
    }
  };
}

function intersperseWith(xx, separator) {
  let beforeEach = (xx, separator) => (() => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let x = match._0;
    let xx$1 = beforeEach(match._1, separator);
    return {
      TAG: "Next",
      _0: separator(),
      _1: () => ({
        TAG: "Next",
        _0: x,
        _1: xx$1
      })
    };
  });
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return {
        TAG: "Next",
        _0: match._0,
        _1: beforeEach(match._1, separator)
      };
    }
  };
}

function intersperse(xx, separator) {
  return intersperseWith(xx, () => separator);
}

function cache(xx) {
  let f = () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return {
        TAG: "Next",
        _0: match._0,
        _1: cache(match._1)
      };
    }
  };
  let f$1 = Lazy.from_fun(() => f());
  return () => Lazy.force(f$1);
}

function allPairs(xx, yy) {
  let yy$1 = cache(yy);
  return flatMap(xx, x => map(yy$1, y => [
    x,
    y
  ]));
}

function dropUntil(xx, f) {
  return () => Option.getOr(Option.map(find(headTails(xx), param => f(param[0])), param => ({
    TAG: "Next",
    _0: param[0],
    _1: param[1]
  })), "End");
}

function dropWhile(xx, f) {
  return () => Option.getOr(Option.map(find(headTails(xx), param => false === f(param[0])), param => ({
    TAG: "Next",
    _0: param[0],
    _1: param[1]
  })), "End");
}

function window(xx, length) {
  if (length <= 0) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "'window' requires a length > 0. You asked for " + length.toString(),
      Error: new Error()
    };
  }
  return filter(scan(xx, [], (sum, val) => {
    if (sum.length >= length) {
      sum.shift();
    }
    sum.push(val);
    return sum;
  }), i => i.length === length);
}

function reduce(xx, zero, concat) {
  let sum = {
    contents: zero
  };
  forEach(xx, x => {
    sum.contents = concat(sum.contents, x);
  });
  return sum.contents;
}

function reduceUntil(xx, zero, concat, predicate) {
  let _xx = xx;
  let _sum = zero;
  while (true) {
    let sum = _sum;
    let xx$1 = _xx;
    if (predicate(sum)) {
      return sum;
    }
    let match = uncons(xx$1);
    if (match === undefined) {
      return sum;
    }
    _sum = concat(sum, match[0]);
    _xx = match[1];
    continue;
  };
}

function reduceWhile(xx, zero, concat, predicate) {
  if (predicate(zero)) {
    let _xx = xx;
    let _sum = zero;
    while (true) {
      let sum = _sum;
      let xx$1 = _xx;
      let match = uncons(xx$1);
      if (match === undefined) {
        return Primitive_option.some(sum);
      }
      let sum$p = concat(sum, match[0]);
      if (!predicate(sum$p)) {
        return Primitive_option.some(sum);
      }
      _sum = sum$p;
      _xx = match[1];
      continue;
    };
  }
  
}

function sumBy(xx, concat) {
  let match = uncons(xx);
  if (match === undefined) {
    return;
  }
  let sum = {
    contents: match[0]
  };
  forEach(match[1], x => {
    sum.contents = concat(sum.contents, x);
  });
  return Primitive_option.some(sum.contents);
}

function prefixSum(xx, accumulator) {
  return () => {
    let match = uncons(xx);
    if (match === undefined) {
      return "End";
    }
    let x = match[0];
    let xx$1 = unfold([
      x,
      match[1]
    ], param => {
      let match = uncons(param[1]);
      if (match === undefined) {
        return;
      }
      let sum$p = accumulator(param[0], match[0]);
      return [
        sum$p,
        [
          sum$p,
          match[1]
        ]
      ];
    });
    return {
      TAG: "Next",
      _0: x,
      _1: xx$1
    };
  };
}

function join(xx, separator) {
  let match = separator.length;
  return reduce(match !== 0 ? intersperseWith(xx, () => separator) : xx, "", (total, i) => total + i);
}

function last(xx) {
  return sumBy(xx, (param, i) => i);
}

function toArray(xx) {
  return reduce(xx, [], (xx, i) => {
    xx.push(i);
    return xx;
  });
}

function some(xx, f) {
  return Option.isSome(find(xx, f));
}

function every(xx, f) {
  return Option.isNone(find(xx, i => !f(i)));
}

function findMap(xx, f) {
  let _xx = xx;
  while (true) {
    let xx$1 = _xx;
    let match = xx$1();
    if (typeof match !== "object") {
      return;
    }
    let x = f(match._0);
    if (x !== undefined) {
      return Primitive_option.some(Primitive_option.valFromOption(x));
    }
    _xx = match._1;
    continue;
  };
}

function findMapLast(xx, f) {
  let _xx = xx;
  let _last;
  while (true) {
    let last = _last;
    let xx$1 = _xx;
    let match = xx$1();
    if (typeof match !== "object") {
      return last;
    }
    let xx$2 = match._1;
    let found = f(match._0);
    if (found !== undefined) {
      _last = found;
      _xx = xx$2;
      continue;
    }
    _xx = xx$2;
    continue;
  };
}

function map2(xx, yy, f) {
  return () => {
    let xx$1 = uncons(xx);
    let yy$1 = uncons(yy);
    return Option.getOr(Seq__Option.map2(xx$1, yy$1, (param, param$1) => ({
      TAG: "Next",
      _0: f(param[0], param$1[0]),
      _1: map2(param[1], param$1[1], f)
    })), "End");
  };
}

function map3(xx, yy, zz, f) {
  return () => {
    let xx$1 = uncons(xx);
    let yy$1 = uncons(yy);
    let zz$1 = uncons(zz);
    return Option.getOr(Seq__Option.map3(xx$1, yy$1, zz$1, (param, param$1, param$2) => ({
      TAG: "Next",
      _0: f(param[0], param$1[0], param$2[0]),
      _1: map3(param[1], param$1[1], param$2[1], f)
    })), "End");
  };
}

function map4(xx, yy, zz, qq, f) {
  return () => {
    let xx$1 = uncons(xx);
    let yy$1 = uncons(yy);
    let zz$1 = uncons(zz);
    let qq$1 = uncons(qq);
    return Option.getOr(Seq__Option.map4(xx$1, yy$1, zz$1, qq$1, (param, param$1, param$2, param$3) => ({
      TAG: "Next",
      _0: f(param[0], param$1[0], param$2[0], param$3[0]),
      _1: map4(param[1], param$1[1], param$2[1], param$3[1], f)
    })), "End");
  };
}

function map5(xx, yy, zz, qq, mm, f) {
  return () => {
    let xx$1 = uncons(xx);
    let yy$1 = uncons(yy);
    let zz$1 = uncons(zz);
    let qq$1 = uncons(qq);
    let mm$1 = uncons(mm);
    return Option.getOr(Seq__Option.map5(xx$1, yy$1, zz$1, qq$1, mm$1, (param, param$1, param$2, param$3, param$4) => ({
      TAG: "Next",
      _0: f(param[0], param$1[0], param$2[0], param$3[0], param$4[0]),
      _1: map5(param[1], param$1[1], param$2[1], param$3[1], param$4[1], f)
    })), "End");
  };
}

function zip(xx, yy) {
  return map2(xx, yy, (x, y) => [
    x,
    y
  ]);
}

function zip3(xx, yy, zz) {
  return map3(xx, yy, zz, (x, y, z) => [
    x,
    y,
    z
  ]);
}

function zip4(xx, yy, zz, qq) {
  return map4(xx, yy, zz, qq, (x, y, z, q) => [
    x,
    y,
    z,
    q
  ]);
}

function zip5(xx, yy, zz, qq, mm) {
  return map5(xx, yy, zz, qq, mm, (x, y, z, q, m) => [
    x,
    y,
    z,
    q,
    m
  ]);
}

function equals(xx, yy, eq) {
  let xx$1 = concat(map(xx, x => Primitive_option.some(x)), () => ({
    TAG: "Next",
    _0: undefined,
    _1: empty
  }));
  let yy$1 = concat(map(yy, y => Primitive_option.some(y)), () => ({
    TAG: "Next",
    _0: undefined,
    _1: empty
  }));
  return every(map2(xx$1, yy$1, (x, y) => {
    if (x !== undefined) {
      if (y !== undefined) {
        return eq(Primitive_option.valFromOption(x), Primitive_option.valFromOption(y));
      } else {
        return false;
      }
    } else {
      return y === undefined;
    }
  }), i => i);
}

function compare(xx, yy, cmp) {
  let xx$1 = concat(map(xx, x => Primitive_option.some(x)), () => ({
    TAG: "Next",
    _0: undefined,
    _1: empty
  }));
  let yy$1 = concat(map(yy, y => Primitive_option.some(y)), () => ({
    TAG: "Next",
    _0: undefined,
    _1: empty
  }));
  return Option.getOr(find(map2(xx$1, yy$1, (x, y) => {
    if (x !== undefined) {
      if (y !== undefined) {
        return cmp(Primitive_option.valFromOption(x), Primitive_option.valFromOption(y));
      } else {
        return 1.0;
      }
    } else if (y !== undefined) {
      return -1.0;
    } else {
      return 0.0;
    }
  }), i => i !== 0.0), 0.0);
}

function length(xx) {
  return reduce(xx, 0, (sum, param) => sum + 1 | 0);
}

function isEmpty(xx) {
  let match = xx();
  return typeof match !== "object";
}

function tail(xx) {
  return () => {
    let match = uncons(xx);
    if (match !== undefined) {
      return match[1]();
    } else {
      return "End";
    }
  };
}

function tails(xx) {
  let xx$1 = unfold(xx, xx => {
    let match = xx();
    if (typeof match !== "object") {
      return;
    }
    let xx$1 = match._1;
    return [
      xx$1,
      xx$1
    ];
  });
  return () => ({
    TAG: "Next",
    _0: xx,
    _1: xx$1
  });
}

function minBy(xx, cmp) {
  return sumBy(xx, (sum, i) => {
    if (cmp(i, sum) < 0.0) {
      return i;
    } else {
      return sum;
    }
  });
}

function maxBy(xx, cmp) {
  return sumBy(xx, (sum, i) => {
    if (cmp(i, sum) > 0.0) {
      return i;
    } else {
      return sum;
    }
  });
}

function interleave(xx, yy) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return yy();
    } else {
      return {
        TAG: "Next",
        _0: match._0,
        _1: interleave(yy, match._1)
      };
    }
  };
}

function exactlyOne(xx) {
  let match = uncons(xx);
  if (match !== undefined && isEmpty(match[1])) {
    return Primitive_option.some(match[0]);
  }
  
}

function pairAhead(xx) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    } else {
      return unfold([
        match._0,
        match._1
      ], nxt => {
        if (nxt === undefined) {
          return;
        }
        let x = nxt[0];
        let match = nxt[1]();
        if (typeof match !== "object") {
          return [
            [
              x,
              undefined
            ],
            undefined
          ];
        }
        let x$p = match._0;
        return [
          [
            x,
            Primitive_option.some(x$p)
          ],
          [
            x$p,
            match._1
          ]
        ];
      })();
    }
  };
}

function pairBehind(xx) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let a = match._0;
    let xx$1 = unfold([
      a,
      match._1
    ], param => {
      let match = param[1]();
      if (typeof match !== "object") {
        return;
      }
      let b = match._0;
      return [
        [
          Primitive_option.some(param[0]),
          b
        ],
        [
          b,
          match._1
        ]
      ];
    });
    let x = [
      undefined,
      a
    ];
    return (() => ({
      TAG: "Next",
      _0: x,
      _1: xx$1
    }))();
  };
}

function pairwise(xx) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let match$1 = match._1();
    if (typeof match$1 !== "object") {
      return "End";
    }
    let b = match$1._0;
    let xx$1 = unfold([
      b,
      match$1._1
    ], param => {
      let match = param[1]();
      if (typeof match !== "object") {
        return;
      }
      let x = match._0;
      return [
        [
          param[0],
          x
        ],
        [
          x,
          match._1
        ]
      ];
    });
    let x_0 = match._0;
    let x = [
      x_0,
      b
    ];
    return (() => ({
      TAG: "Next",
      _0: x,
      _1: xx$1
    }))();
  };
}

function dropLast(xx, n) {
  if (n === 0) {
    return xx;
  }
  if (n < 0) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "dropLast requires a count of 0 or more. You requested " + n.toString(),
      Error: new Error()
    };
  }
  return () => map(takeWhile(dropUntil(scan(xx, [], (sum, i) => {
    sum.push(i);
    let size = sum.length;
    if (size > (n + 1 | 0)) {
      sum.shift();
    }
    return sum;
  }), i => i.length === (n + 1 | 0)), i => i.length > n), i => i[0])();
}

function neighbors(xx) {
  return () => {
    let match = xx();
    if (typeof match !== "object") {
      return "End";
    }
    let a = match._0;
    let match$1 = match._1();
    if (typeof match$1 !== "object") {
      return {
        TAG: "Next",
        _0: [
          undefined,
          a,
          undefined
        ],
        _1: empty
      };
    }
    let b = match$1._0;
    let match$2 = match$1._1();
    if (typeof match$2 !== "object") {
      let x_0 = Primitive_option.some(a);
      let x = [
        x_0,
        b,
        undefined
      ];
      return {
        TAG: "Next",
        _0: [
          undefined,
          a,
          Primitive_option.some(b)
        ],
        _1: () => ({
          TAG: "Next",
          _0: x,
          _1: empty
        })
      };
    }
    let c = match$2._0;
    let xx$1 = unfold([
      b,
      c,
      match$2._1
    ], state => {
      if (state === undefined) {
        return;
      }
      let c = state[1];
      let b = state[0];
      let match = state[2]();
      if (typeof match !== "object") {
        return [
          [
            Primitive_option.some(b),
            c,
            undefined
          ],
          undefined
        ];
      }
      let d = match._0;
      return [
        [
          Primitive_option.some(b),
          c,
          Primitive_option.some(d)
        ],
        [
          c,
          d,
          match._1
        ]
      ];
    });
    let x_0$1 = Primitive_option.some(a);
    let x_2 = Primitive_option.some(c);
    let x$1 = [
      x_0$1,
      b,
      x_2
    ];
    let xx$2 = () => ({
      TAG: "Next",
      _0: x$1,
      _1: xx$1
    });
    let x_2$1 = Primitive_option.some(b);
    let x$2 = [
      undefined,
      a,
      x_2$1
    ];
    return (() => ({
      TAG: "Next",
      _0: x$2,
      _1: xx$2
    }))();
  };
}

function isSortedBy(xx, cmp) {
  return every(pairwise(xx), param => cmp(param[0], param[1]) <= 0.0);
}

function everyOk(xx) {
  let concat$1 = (sum, i) => {
    if (sum.TAG !== "Ok") {
      return sum;
    }
    if (i.TAG !== "Ok") {
      return i;
    }
    let ok = i._0;
    return {
      TAG: "Ok",
      _0: concat(sum._0, () => ({
        TAG: "Next",
        _0: ok,
        _1: empty
      }))
    };
  };
  return reduceUntil(xx, {
    TAG: "Ok",
    _0: empty
  }, concat$1, Result.isError);
}

function everySome(xx) {
  let concat$1 = (sum, i) => {
    if (sum === undefined) {
      return;
    }
    if (i === undefined) {
      return;
    }
    let some = Primitive_option.valFromOption(i);
    return concat(sum, () => ({
      TAG: "Next",
      _0: some,
      _1: empty
    }));
  };
  return reduceUntil(xx, empty, concat$1, Option.isNone);
}

function toOption(xx) {
  let match = xx();
  if (typeof match !== "object") {
    return;
  }
  let xx$1 = match._1;
  let x = match._0;
  return () => ({
    TAG: "Next",
    _0: x,
    _1: xx$1
  });
}

function consume(xx) {
  forEach(xx, param => {});
}

function orElse(xx, yy) {
  return () => {
    let nxt = xx();
    if (typeof nxt !== "object") {
      return yy();
    } else {
      return nxt;
    }
  };
}

function reverse(xx) {
  let generator = () => {
    let xx$1 = toArray(xx);
    let match = xx$1.length;
    if (match !== 0) {
      return fromArray(xx$1.length - 1 | 0, 0, xx$1);
    } else {
      return empty;
    }
  };
  return () => generator()();
}

function sortBy(xx, compare) {
  let generator = () => {
    let xx$1 = toArray(xx);
    xx$1.sort(compare);
    return fromArray(undefined, undefined, xx$1);
  };
  return () => generator()();
}

function helper(xx, maxSize, f) {
  if (maxSize <= 0) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "Size must be 1 or more. You asked for " + maxSize.toString() + ".",
      Error: new Error()
    };
  }
  return flatten(unfold([
    empty,
    xx
  ], param => {
    let sum = param[0];
    let match = uncons(param[1]);
    if (match === undefined) {
      return;
    }
    let x = match[0];
    let xOnly_1 = () => ({
      TAG: "Next",
      _0: x,
      _1: empty
    });
    let xOnly = [
      1,
      xOnly_1
    ];
    let xWithSum = flatMap(sum, param => {
      let size = param[0];
      if (size < maxSize) {
        return map(f(x, param[1]), xx => [
          size + 1 | 0,
          xx
        ]);
      } else {
        return empty;
      }
    });
    let next = () => ({
      TAG: "Next",
      _0: xOnly,
      _1: xWithSum
    });
    return [
      next,
      [
        concat(sum, next),
        match[1]
      ]
    ];
  }));
}

function permutations(xx, maxSize) {
  return helper(xx, maxSize, (x, xx) => {
    let go = (pre, suf) => unfold([
      pre,
      suf
    ], param => {
      let pre = param[0];
      let match = uncons(param[1]);
      if (match === undefined) {
        return;
      }
      let xx = match[1];
      let x$1 = match[0];
      let $$yield = concat(concat(concat(pre, () => ({
        TAG: "Next",
        _0: x$1,
        _1: empty
      })), () => ({
        TAG: "Next",
        _0: x,
        _1: empty
      })), xx);
      let next_0 = concat(pre, () => ({
        TAG: "Next",
        _0: x$1,
        _1: empty
      }));
      let next = [
        next_0,
        xx
      ];
      return [
        $$yield,
        next
      ];
    });
    let x$1 = () => ({
      TAG: "Next",
      _0: x,
      _1: xx
    });
    return concat(go(empty, xx), () => ({
      TAG: "Next",
      _0: x$1,
      _1: empty
    }));
  });
}

function combinations(xx, maxSize) {
  return helper(xx, maxSize, (x, xx) => {
    let x$1 = () => ({
      TAG: "Next",
      _0: x,
      _1: xx
    });
    return () => ({
      TAG: "Next",
      _0: x$1,
      _1: empty
    });
  });
}

function toList(xx) {
  return reduce(reverse(xx), /* [] */0, List.add);
}

function split(xx, init, acc) {
  let unfolder = _state => {
    while (true) {
      let state = _state;
      if (state === undefined) {
        return;
      }
      let sum = state[0];
      let match = uncons(state[1]);
      if (match === undefined) {
        return [
          sum,
          undefined
        ];
      }
      let xx = match[1];
      let x = match[0];
      let sum$1 = acc(sum, x);
      if (sum$1 === undefined) {
        return [
          sum,
          [
            init(x),
            xx
          ]
        ];
      }
      _state = [
        Primitive_option.valFromOption(sum$1),
        xx
      ];
      continue;
    };
  };
  return () => {
    let match = uncons(xx);
    if (match !== undefined) {
      return unfold([
        init(match[0]),
        match[1]
      ], unfolder)();
    } else {
      return "End";
    }
  };
}

function chunkBySize(xx, length) {
  if (length <= 0) {
    throw {
      RE_EXN_ID: InvalidArgument,
      _1: "chunkBySize requires a length > 0. You asked for " + length.toString(),
      Error: new Error()
    };
  }
  return split(xx, i => [i], (sum, i) => {
    if (sum.length === length) {
      return;
    } else {
      sum.push(i);
      return sum;
    }
  });
}

function at(xx, inx) {
  let _xx = xx;
  let _inxCurrent = 0;
  while (true) {
    let inxCurrent = _inxCurrent;
    let xx$1 = _xx;
    let match = xx$1();
    if (typeof match !== "object") {
      return;
    }
    if (inxCurrent === inx) {
      return Primitive_option.some(match._0);
    }
    _inxCurrent = inxCurrent + 1 | 0;
    _xx = match._1;
    continue;
  };
}

function iterateWhile(seed, f) {
  return () => {
    let go = seed => (() => {
      let seed$1 = f(seed);
      if (seed$1 === undefined) {
        return "End";
      }
      let seed$2 = Primitive_option.valFromOption(seed$1);
      return {
        TAG: "Next",
        _0: seed$2,
        _1: go(seed$2)
      };
    });
    return {
      TAG: "Next",
      _0: seed,
      _1: go(seed)
    };
  };
}

function unfoldMany(seed, f) {
  return orElse(flatMap(f(seed), param => {
    let n = param[0];
    return map(unfoldMany(param[1], f), result => (() => ({
      TAG: "Next",
      _0: n,
      _1: result
    })));
  }), () => ({
    TAG: "Next",
    _0: empty,
    _1: empty
  }));
}

let append = concat;

export {
  InvalidArgument,
  empty,
  once,
  onceWith,
  unfold,
  unfoldMany,
  init,
  replicate,
  replicateWith,
  forever,
  foreverWith,
  iterate,
  iterateWhile,
  cycle,
  range,
  rangeMap,
  fromArray,
  fromList,
  cons,
  prepend,
  concat,
  append,
  flatten,
  flatMap,
  map,
  mapi,
  indexed,
  filter,
  filteri,
  filterMap,
  filterMapi,
  filterSome,
  filterOk,
  take,
  takeWhile,
  takeUntil,
  drop,
  dropWhile,
  dropUntil,
  scan,
  cache,
  tap,
  chunkBySize,
  pairwise,
  window,
  allPairs,
  intersperse,
  intersperseWith,
  orElse,
  map2,
  map3,
  map4,
  map5,
  zip,
  zip3,
  zip4,
  zip5,
  sortedMerge,
  interleave,
  reduce,
  reduceUntil,
  reduceWhile,
  sumBy,
  prefixSum,
  forEach,
  forEachi,
  some,
  every,
  find,
  findLast,
  findMap,
  findMapLast,
  length,
  isEmpty,
  isSortedBy,
  equals,
  compare,
  head,
  tail,
  tails,
  dropLast,
  uncons,
  minBy,
  maxBy,
  last,
  toArray,
  toList,
  join,
  exactlyOne,
  toOption,
  everyOk,
  everySome,
  consume,
  reverse,
  delay,
  sortBy,
  combinations,
  permutations,
  split,
  pairAhead,
  pairBehind,
  neighbors,
  at,
}
/* No side effect */
