// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/Array.js";
import * as Option from "rescript/lib/es6/Option.js";

function category(i) {
  return i.category;
}

function title(i) {
  return i.title;
}

function expectation(i) {
  return i.expectation;
}

function hasKeyword(i, word) {
  let match = (text, word) => {
    let text$1 = text.trim().toLocaleLowerCase();
    let keyword = word.trim().toLocaleLowerCase();
    return text$1.includes(keyword);
  };
  if (match(i.category, word) || match(i.title, word)) {
    return true;
  } else {
    return Option.mapOr(i.expectation, false, expectation => match(expectation, word));
  }
}

function cmp(a, b) {
  let x = a.category + a.title;
  let y = b.category + b.title;
  if (x < y) {
    return -1.0;
  } else if (x > y) {
    return 1.0;
  } else {
    return 0.0;
  }
}

function fromResult(category, title, expectation, predicate) {
  return {
    category: category,
    title: title,
    expectation: expectation,
    predicate: () => {
      let tmp;
      try {
        tmp = predicate();
      } catch (exn) {
        tmp = {
          TAG: "Error",
          _0: "An exception was raised and not caught by the test itself."
        };
      }
      return Promise.resolve(tmp);
    }
  };
}

function fromPredicate(category, title, expectation, predicate) {
  return fromResult(category, title, expectation, () => {
    try {
      if (predicate()) {
        return {
          TAG: "Ok",
          _0: undefined
        };
      } else {
        return {
          TAG: "Error",
          _0: ""
        };
      }
    } catch (exn) {
      return {
        TAG: "Error",
        _0: "An exception was raised and not caught by the test itself."
      };
    }
  });
}

function expectThrow(category, title, expectation, f) {
  return fromPredicate(category, title, expectation, () => {
    try {
      f();
      return false;
    } catch (exn) {
      return true;
    }
  });
}

function expectNotThrow(category, title, expectation, f) {
  return fromPredicate(category, title, expectation, () => {
    try {
      f();
      return true;
    } catch (exn) {
      return false;
    }
  });
}

function fromResultAsync(category, title, expectation, predicate) {
  return {
    category: category,
    title: title,
    expectation: expectation,
    predicate: predicate
  };
}

function fromPredicateAsync(category, title, expectation, predicate) {
  return fromResultAsync(category, title, expectation, () => predicate().then(success => Promise.resolve(success ? ({
      TAG: "Ok",
      _0: undefined
    }) : ({
      TAG: "Error",
      _0: ""
    }))));
}

async function run(i) {
  try {
    let succeed = await i.predicate();
    return [
      succeed,
      i
    ];
  } catch (exn) {
    return [
      {
        TAG: "Error",
        _0: "An exception was raised and not caught by the test itself."
      },
      i
    ];
  }
}

function toSummaryString(i) {
  let expectation = i.expectation;
  let expectation$1 = expectation !== undefined ? "| " + expectation : "";
  return i.category + " | " + i.title + " " + expectation$1;
}

function toDetailString(i, message) {
  let message$1 = message === "" ? "" : "\n" + message;
  let expectation = i.expectation;
  let expectation$1 = expectation !== undefined ? "| " + expectation : "";
  return "\n==== FAIL " + i.category + " | " + i.title + " " + expectation$1 + " ====" + message$1;
}

async function runSuite(filterOpt, onlyShowFailuresOpt, tests) {
  let filter = filterOpt !== undefined ? filterOpt : param => true;
  let onlyShowFailures = onlyShowFailuresOpt !== undefined ? onlyShowFailuresOpt : false;
  let logSection = n => {
    console.log("");
    console.log("==== " + n + " ====");
  };
  let results = await Promise.all(tests.filter(filter).toSorted(cmp).map(run));
  let succeeded = $$Array.filterMap(results, param => {
    if (param[0].TAG === "Ok") {
      return param[1];
    }
    
  });
  let failed = $$Array.filterMap(results, param => {
    let r = param[0];
    if (r.TAG === "Ok") {
      return;
    } else {
      return [
        param[1],
        r._0
      ];
    }
  });
  if (succeeded.length > 0 && !onlyShowFailures) {
    logSection("SUCCEEDED");
    succeeded.forEach(t => {
      let prim = "PASS " + toSummaryString(t);
      console.log(prim);
    });
  }
  if (failed.length > 0) {
    failed.forEach(param => {
      let prim = toDetailString(param[0], param[1]);
      console.log(prim);
    });
    logSection("FAILURE SUMMARY");
    failed.forEach(param => {
      let prim = "FAIL  " + toSummaryString(param[0]);
      console.log(prim);
    });
  }
  logSection("SUMMARY");
  let summary_pass = succeeded.length;
  let summary_fail = failed.length;
  let summary_ran = succeeded.length + failed.length | 0;
  let summary = {
    pass: summary_pass,
    fail: summary_fail,
    ran: summary_ran
  };
  let prim = "PASS : " + summary_pass.toString();
  console.log(prim);
  let prim$1 = "FAIL : " + summary_fail.toString();
  console.log(prim$1);
  let prim$2 = "RAN  : " + summary_ran.toString();
  console.log(prim$2);
  console.log("");
  return summary;
}

export {
  fromResult,
  fromPredicate,
  expectThrow,
  expectNotThrow,
  fromPredicateAsync,
  fromResultAsync,
  category,
  title,
  expectation,
  hasKeyword,
  runSuite,
}
/* No side effect */
