// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "rescript/lib/es6/Promise.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function make(promise, onError) {
  return () => $$Promise.$$catch(promise(), e => Promise.resolve(onError(e)));
}

function map(t, f) {
  return () => t().then(r => Promise.resolve(f(r)));
}

function toPromise(t) {
  return t();
}

let forEach = map;

function spy(t, effect) {
  return () => t().then(r => {
    effect(r);
    return Promise.resolve(r);
  });
}

function make$1(promise, onError) {
  return make(() => promise().then(ok => Promise.resolve({
    TAG: "Ok",
    _0: ok
  })), e => ({
    TAG: "Error",
    _0: onError(e)
  }));
}

function mapError(t, f) {
  return () => t().then(r => {
    let tmp;
    tmp = r.TAG === "Ok" ? r : ({
        TAG: "Error",
        _0: f(r._0)
      });
    return Promise.resolve(tmp);
  });
}

function mapOk(t, f) {
  return () => t().then(r => {
    let tmp;
    tmp = r.TAG === "Ok" ? ({
        TAG: "Ok",
        _0: f(r._0)
      }) : r;
    return Promise.resolve(tmp);
  });
}

function flatMap(t, f) {
  return () => t().then(r => {
    let tmp;
    tmp = r.TAG === "Ok" ? f(r._0) : r;
    return Promise.resolve(tmp);
  });
}

function toOption(t) {
  return () => t().then(r => {
    let tmp;
    tmp = r.TAG === "Ok" ? Primitive_option.some(r._0) : undefined;
    return Promise.resolve(tmp);
  });
}

let Result = {
  make: make$1,
  mapError: mapError,
  mapOk: mapOk,
  flatMap: flatMap,
  toOption: toOption
};

export {
  make,
  map,
  toPromise,
  forEach,
  spy,
  Result,
}
/* No side effect */
