// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Seq from "./Seq.mjs";
import * as Option from "rescript/lib/es6/Option.js";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

let arr = [
  "w",
  "v",
  "q",
  "s",
  "p",
  "x"
];

let s1 = Seq.fromArray(undefined, undefined, arr);

let s2 = Seq.fromArray(2, undefined, arr);

let s3 = Seq.fromArray(undefined, 4, arr);

let aa = Seq.range(1, 100);

let bb = Seq.rangeMap(99, 1, i => Math.imul(i, 3));

let cc = Seq.takeWhile(Seq.iterate(2, i => (i << 1)), i => i < 1000);

let dd = Seq.foreverWith(() => Math.random());

let ee = Seq.replicate("x", 100);

let nums = Seq.forEach(Seq.filter(Seq.flatMap(Seq.tap(Seq.takeUntil(Seq.filterMap(Seq.dropLast(Seq.pairwise(Seq.map(Seq.drop(Seq.range(1, 999999), 33), n => Math.imul(n, 3) % 7)), 2), param => {
  let b = param[1];
  let a = param[0];
  if (a < b) {
    return a + b | 0;
  }
  
}), i => i > 200), n => {
  if (n === 100) {
    console.log("Saw 100; interesting!");
    return;
  }
  
}), n => Seq.rangeMap(1, n, i => (i << 1))), n => n > 100), prim => {
  console.log(prim);
});

function runningTotal(nums) {
  return Seq.scan(Seq.fromArray(undefined, undefined, nums), 0, (sum, i) => sum + i | 0);
}

function parity(n) {
  if (n % 2 === 0) {
    return "even";
  } else {
    return "odd";
  }
}

function evensAndOdds(nums) {
  return Seq.split(nums, i => ({
    parity: parity(i),
    count: 1
  }), (sum, i) => {
    if (parity(i) === sum.parity) {
      return {
        parity: sum.parity,
        count: sum.count + 1 | 0
      };
    }
    
  });
}

function removeDups(xx) {
  return Seq.map(Seq.filter(Seq.pairBehind(Seq.fromArray(undefined, undefined, xx)), param => {
    let b = param[1];
    return Option.mapOr(param[0], true, a => Primitive_object.notequal(a, b));
  }), param => param[1]);
}

function sortByEmployee(a, b) {
  let a$1 = a.empId;
  let b$1 = b.empId;
  return a$1.localeCompare(b$1);
}

function salesSummary(sales) {
  return Seq.split(Seq.fromArray(undefined, undefined, sales.toSorted(sortByEmployee)), i => ({
    empId: i.empId,
    sales: 1,
    revenue: i.amount
  }), (sum, i) => {
    if (sum.empId === i.empId) {
      return {
        empId: sum.empId,
        sales: sum.sales + 1 | 0,
        revenue: sum.revenue + i.amount | 0
      };
    }
    
  });
}

function validate(docs, isValidEmail) {
  let titles = Seq.everyOk(Seq.map(Seq.fromArray(undefined, undefined, docs), doc => {
    if (isValidEmail(doc.email)) {
      return {
        TAG: "Ok",
        _0: doc.title.trim()
      };
    } else {
      return {
        TAG: "Error",
        _0: "The email is invalid for document: " + doc.title
      };
    }
  }));
  if (titles.TAG === "Ok") {
    return Seq.forEach(titles._0, t => {
      console.log("Is valid: " + t);
    });
  }
  console.log("Document with title " + titles._0 + " is not valid.");
}

function binary(n) {
  return Seq.toArray(Seq.unfold(n, value => {
    if (value > 0) {
      return [
        value % 2,
        value / 2 | 0
      ];
    }
    
  })).toReversed();
}

function fibonacci(count) {
  return Seq.toArray(Seq.take(Seq.prepend(Seq.unfold([
    0,
    1
  ], param => {
    let b = param[1];
    let a = param[0];
    if ((a + b | 0) <= 100) {
      return [
        a + b | 0,
        [
          b,
          a + b | 0
        ]
      ];
    }
    
  }), Seq.fromArray(undefined, undefined, [
    0,
    1
  ])), count));
}

function zipLongest(xx, yy) {
  let optionForever = ss => Seq.concat(Seq.map(ss, x => Primitive_option.some(x)), Seq.forever(undefined));
  let xx$1 = optionForever(xx);
  let yy$1 = optionForever(yy);
  return Seq.takeWhile(Seq.zip(xx$1, yy$1), param => {
    if (Option.isSome(param[0])) {
      return true;
    } else {
      return Option.isSome(param[1]);
    }
  });
}

function x(param) {
  return param[0];
}

function y(param) {
  return param[1];
}

function toString(param) {
  return "(" + param[0].toString() + ", " + param[1].toString() + ")";
}

let Point = {
  x: x,
  y: y,
  toString: toString
};

function localMinimums(points) {
  return Option.getOr(Option.map(Seq.toOption(Seq.map(Seq.filterMap(Seq.window(Seq.fromArray(undefined, undefined, points), 3), pp => {
    if (y(pp[1]) < y(pp[0]) && y(pp[1]) < y(pp[2])) {
      return pp[1];
    }
    
  }), toString)), pp => Seq.join(pp, ", ")), "There are no local minimums.");
}

let multiplicationTable = Seq.toArray(Seq.map(Seq.range(0, 10), x => Seq.toArray(Seq.map(Seq.range(0, 10), y => Math.imul(x, y)))));

export {
  arr,
  s1,
  s2,
  s3,
  aa,
  bb,
  cc,
  dd,
  ee,
  nums,
  runningTotal,
  parity,
  evensAndOdds,
  removeDups,
  sortByEmployee,
  salesSummary,
  validate,
  binary,
  fibonacci,
  zipLongest,
  Point,
  localMinimums,
  multiplicationTable,
}
/* s1 Not a pure module */
