// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function map2(a, b, m) {
  if (a !== undefined && b !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b)));
  }
  
}

function map3(a, b, c, m) {
  if (a !== undefined && b !== undefined && c !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b), Primitive_option.valFromOption(c)));
  }
  
}

function map4(a, b, c, d, m) {
  if (a !== undefined && b !== undefined && c !== undefined && d !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b), Primitive_option.valFromOption(c), Primitive_option.valFromOption(d)));
  }
  
}

function map5(a, b, c, d, e, m) {
  if (a !== undefined && b !== undefined && c !== undefined && d !== undefined && e !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b), Primitive_option.valFromOption(c), Primitive_option.valFromOption(d), Primitive_option.valFromOption(e)));
  }
  
}

export {
  map2,
  map3,
  map4,
  map5,
}
/* No side effect */
